// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    insertSql: function(table, fields) {
      var key, sql, value, _args, _fields, _values;
      fields.create_time = Date.now();
      _fields = _args = "";
      _values = [];
      for (key in fields) {
        value = fields[key];
        _fields += "`" + key + "`,";
        _args += "?,";
        _values.push(value);
      }
      sql = "insert into " + table + " (" + (_fields.slice(0, -1)) + ") values (" + (_args.slice(0, -1)) + ")";
      return [sql, _values];
    },
    updateSql: function(table, id, fields) {
      var name, sql, val, _sets, _values;
      _sets = "";
      _values = [];
      for (name in fields) {
        val = fields[name];
        _sets += "`" + name + "`=?,";
        _values.push(val);
      }
      _values.push(id);
      sql = "update " + table + " " + (_sets.slice(0, -1)) + " where id = ?";
      return [sql, _values];
    },
    selectSql: function(table, where) {
      var sql;
      sql = "select * from " + table + " where " + where[0] + "=?";
      return [sql, [where[1]]];
    }
  };

}).call(this);
