// Generated by CoffeeScript 1.6.3
(function() {
  var Battle, Player, async, battleLog, playerManager, table;

  table = require('../../../common/table');

  Battle = require('../../../battle/battle');

  battleLog = require('../../../battle/battleLog');

  Player = require('../../../battle/player');

  async = require('async');

  playerManager = require('../../../manager/playerManager');

  exports.pve = function(args, callback) {
    var pid, taskData, taskId;
    pid = args.pid;
    taskId = args.taskId;
    taskData = table.getTableItem('task_config', taskId);
    return async.waterfall([
      function(cb) {
        return playerManager.getPlayer({
          pid: pid
        }, cb);
      }, function(playerEntity, cb) {
        var attacker, battle, defender;
        attacker = new Player(playerEntity);
        defender = new Player(taskData);
        battleLog = clear();
        battle = new Battle(attacker, defender);
        battle.process();
        return cb(null, JSON.stringify(battleLog.reports()));
      }
    ], function(err, bl) {
      if (err) {
        return callback(err, null);
      } else {
        return callback(null, bl);
      }
    });
  };

}).call(this);
