// Generated by CoffeeScript 1.6.2
var Magpie, application, fs, path, self;

fs = require('fs');

path = require('path');

application = require('./application');

Magpie = module.exports = {};

Magpie.version = '0.1';

Magpie.events = {
  ADD_SERVERS: '__add_servers__',
  REMOVE_SERVERS: '__remove_servers__',
  NEW_REQ: '__new_request__',
  NEW_RESP: '__new_response__'
};

Magpie.components = {};

self = this;

Magpie.createApp = function(opts) {
  var app;

  app = new Application(opts);
  self.app = app;
  return app;
};

Object.defineProperty(Magpie, 'app', {
  get: function() {
    return self.app;
  }
});

fs.readdirSync(__dirname + '/components').forEach(function(filename) {
  var load, name;

  if (!/\.js$/.test(filename)) {
    return;
  }
  name = path.basename(filename, '.js');
  load = function() {
    return require('./components/' + name);
  };
  Magpie.components.__defineGetter__(name, load);
  return Magpie.__defineGetter__(name, load);
});
