// Generated by CoffeeScript 1.6.2
var ModelBase, Player, exports, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ModelBase = require('./model_base');

Player = (function(_super) {
  __extends(Player, _super);

  function Player() {
    _ref = Player.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Player.configure('id', 'account_id', 'name', 'lv', 'exp', 'power', 'money', 'hero_ids');

  return Player;

})(ModelBase);

exports = module.exports = Player;
