// Generated by CoffeeScript 1.6.3
(function() {
  var exports, _;

  _ = require('underscore');

  exports = module.exports = {
    hitRate: function(rate) {
      var rd;
      rate = parseInt(rate);
      if (isNaN(rate) || rate < 0 && rate > 100) {
        throw new Error("Invilid argument: can't pass " + rate + " to int");
      }
      rd = _.random(0, 100);
      if (rd <= rate) {
        return true;
      } else {
        return false;
      }
    },
    random: function() {
      return _.random(0, 100);
    },
    parseEffect: function(value) {
      var base_val, lv_grow, pattern, _ref;
      pattern = /^\d+,\d+$/;
      if (!pattern.exec(value)) {
        throw new Error("effect value " + value + " is invalid");
      }
      _ref = value.split(','), base_val = _ref[0], lv_grow = _ref[1];
      return [parseInt(base_val), parseInt(lv_grow)];
    }
  };

}).call(this);
