// Generated by CoffeeScript 1.6.3
(function() {
  var Manager, openBox, parseTask, randomCard, table, taskRate, _;

  table = require('./table');

  taskRate = require('../../config/data/taskRate');

  _ = require('underscore');

  Manager = (function() {
    function Manager() {}

    Manager.explore = function(player, app, cb) {
      var exp_to_upgrade, progress, rd, res, task, task_id, _ref, _ref1;
      _ref = parseTask(player.task), task_id = _ref[0], progress = _ref[1];
      task = table.getTableItem('task', task_id);
      exp_to_upgrade = table.getTableItem('player_upgrade', player.lv);
      res = {
        result: 'none',
        power_consume: task.power_consume,
        exp_obtain: task.exp_obtain,
        coins_obtain: task.coins_obtain,
        upgrade: false,
        card_id: null
      };
      rd = _.random(0, 100);
      if (rd <= taskRate.fight) {
        res.result = 'fight';
        app.rpc.battle.fightRemote.pve;
      } else if ((taskRate.fight < rd && rd <= (taskRate.fight + taskRate.precious_box))) {
        res.result = 'box';
        res.card_id = (_ref1 = openBox()) != null ? _ref1.id : void 0;
      } else {
        res.result = 'none';
      }
      player.consumePower(task.power_consume);
      player.increase('money', task.coins_obtain);
      if ((player.exp + task.exp_obtain) >= exp_to_upgrade) {
        player.exp = 0;
        player.increase('lv');
        res.upgrade = true;
      } else {
        player.increase('exp', task.exp_obtain);
      }
      player.save();
      return cb(null, res);
    };

    return Manager;

  })();

  parseTask = function(mark) {
    return mark.split('#');
  };

  openBox = function() {
    var getStar, rd, star;
    star = taskRate.open_box.star;
    rd = _.random(0, 100);
    getStar = function(rd) {
      if (rd <= star.one) {
        return 1;
      }
      if ((star.one < rd && rd <= (star.one + star.two))) {
        return 2;
      }
      if (((star.one + star.two) < rd && rd < (star.one + star.two + star.three))) {
        return 3;
      }
      if ((star.one + star.two + star.three)(rd <= 100)) {
        return 4;
      }
      return 1;
    };
    return randomCard(getStar(rd));
  };

  randomCard = function(star) {
    var ids, index;
    ids = _.range(star, 250, 5);
    index = _.random(0, ids.length);
    return table.getTableItem('cards', ids[index]);
  };

  module.exports = Manager;

}).call(this);
