// Generated by CoffeeScript 1.6.2
var Hero, TABLE_DIR, tab;

Hero = require('../battle/hero');

tab = require('../model/table');

TABLE_DIR = (require('./prepare/path')).TABLE_DIR;

describe('Hero', function() {
  before(function() {
    return tab.reloadTables(TABLE_DIR + 'skills.xml', TABLE_DIR + 'cards.xml');
  });
  it('Initial', function() {
    var hero;

    hero = new Hero({
      id: 1,
      lv: 10,
      star: 1,
      card_id: 1
    });
    hero.id.should.equal(1);
    hero.lv.should.equal(10);
    hero.star.should.equal(1);
    return hero.card_id.should.equal(1);
  });
  it('Death', function() {
    var hero;

    hero = new Hero({
      id: 1,
      lv: 10,
      star: 1,
      card_id: 1,
      skill_lv: 2
    });
    hero.death().should.be["false"];
    hero.hp = 0;
    hero.death().should.be["true"];
    hero.dp = -1;
    return hero.death().should.be["true"];
  });
  return it('create hero, with skill atk_improve', function() {
    var hero;

    hero = new Hero({
      id: 1,
      lv: 10,
      star: 3,
      card_id: 8,
      skill_lv: 2
    });
    return hero.should.be["instanceof"](Hero);
  });
});
