// Generated by CoffeeScript 1.6.2
var Battle, Player, PlayerManager, TABLE_DIR, battleLog, player_data, tab;

Battle = require('../battle/battle');

Player = require('../battle/player');

PlayerManager = require('../model/player');

tab = require('../model/table');

battleLog = require('../battle/battle_log');

player_data = require('./prepare/player.data');

TABLE_DIR = (require('./prepare/path')).TABLE_DIR;

describe('Battle', function() {
  return describe('1 v 1', function() {
    before(function() {
      tab.reloadTables(TABLE_DIR + 'skills.xml', TABLE_DIR + 'cards.xml');
      return player_data.laodTestData();
    });
    after(function() {
      return player_data.clearTestData();
    });
    return it('6 v 6, using skill 2', function() {
      return PlayerManager.fetchMany([player_data.player_id5, player_data.player_id6], function(err, result) {
        var res;

        console.log(err, result);
        this.battle = null;
        this.attacker = new Player(result[player_data.player_id5]);
        this.attacker.setLineUp('00:4,01:9,02:15,10:129,11:195,12:204');
        this.defender = new Player(result[player_data.player_id6]);
        this.defender.setLineUp('00:50,01:54,02:59,10:139,11:174,12:235');
        this.battle = new Battle(this.attacker, this.defender);
        this.battle.process();
        res = battleLog.reports();
        return console.log(JSON.stringify(res));
      });
    });
  });
});
