// Generated by CoffeeScript 1.6.2
var Player, util;

Player = require('../manager/manager').player;

util = require('util');

describe('Player Model', function() {
  return describe('static methods', function() {
    return it('create', function() {
      Player.create({
        id: 'key1',
        name: 'value'
      }, function(err, result) {
        result.set('name', 'wuzhanghai');
        return console.log(err, result);
      });
      return Player.remove('key1', function(err, result) {
        return console.log(err, result);
      });
    });
  });
});
