// Generated by CoffeeScript 1.6.3
var _;

_ = require('underscore');

module.exports.dispatch = function(uid, connectors) {
  var index;
  index = Number(uid) % connectors.length;
  return connectors[index];
};

module.exports.randomDispatch = function(connectors) {
  var index;
  index = _.random(0, connectors.length - 1);
  return connectors[index];
};
