// Generated by CoffeeScript 1.6.3
module.exports = {
  connector: function(session, msg, app, cb) {
    if (!session) {
      cb(new Error('fail to reoute to connector server for session is empty'));
      return;
    }
    if (!session.fontendId) {
      cb(new Error('fail to find fronend id in session'));
      return;
    }
    return cb(null, session.fontendId);
  },
  area: function(session, msg, app, cb) {
    var areas, serverId;
    areas = app.get('areaIdMap');
    serverId = areas[session.get('areaId')];
    if (!serverId) {
      cb(new Error('can not find server info for type: ' + msg.serverType));
      return;
    }
    return cb(null, serverId);
  },
  battle: function(session, msg, app, cb) {
    var battles, serverId;
    battles = app.get('battleIdMap');
    serverId = battles[session.get('areaId')];
    if (!serverId) {
      cb(new Error('can not find server info for type: ' + msg.serverType));
      return;
    }
    return cb(null, serverId);
  }
};
