// login scene res
var login_scene_path = "res/login/";

var login_scene_image = {
    edit1: login_scene_path + "edit1.png",
    edit2: login_scene_path + "edit2.png"
};

var login_scene_res = [
    //image

    //plist

    //fnt

    //tmx

    //bgm

    //effect
];

for (var key in login_scene_image) {
    login_scene_res.push({src: login_scene_image[key]});
}

// main scene res
var main_scene_path = "res/main/";

var main_scene_image = {
    bg1: main_scene_path + "bg1.png",
    bg2: main_scene_path + "bg2.png",
//    bg3: main_scene_path + "bg3.png",
    bg4: main_scene_path + "bg4.png",
    bg5: main_scene_path + "bg5.png",
    bg6: main_scene_path + "bg6.png",
    bg7: main_scene_path + "bg7.png",
    bg8: main_scene_path + "bg8.png",
    bg9: main_scene_path + "bg9.png",
    bg10: main_scene_path + "bg10.png",
    bg11: main_scene_path + "bg11.png",
    bg12: main_scene_path + "bg12.png",
    bg13: main_scene_path + "bg13.png",
//    bg14: main_scene_path + "bg14.png",
    bg15: main_scene_path + "bg15.png",
    bg16: main_scene_path + "bg16.png",
    bg17: main_scene_path + "bg17.png",
    bg18: main_scene_path + "bg18.png",
    bg19: main_scene_path + "bg19.png",

    player_details_bg: main_scene_path + "player_details_bg.png",
    lv_bg: main_scene_path + "lv_bg.png",
    exp_bg: main_scene_path + "exp_bg.png",
    exp: main_scene_path + "exp.png",
    main_message_bg: main_scene_path + "main_message_bg.png",
    star1: main_scene_path + "star1.png",
    star2: main_scene_path + "star2.png",
    star3: main_scene_path + "star3.png",
    ladder1: main_scene_path + "ladder1.png",
    ladder2: main_scene_path + "ladder2.png",
    cloud: main_scene_path + "cloud.png",
    gameFrame: main_scene_path + "gameFrame.png",

    card0: main_scene_path + "card0.png",

    spirit_1_0: main_scene_path + "spirit_1_0.png",
    spirit_1_1: main_scene_path + "spirit_1_1.png",
    spirit_1_2: main_scene_path + "spirit_1_2.png",
    spirit_1_3: main_scene_path + "spirit_1_3.png",
    spirit_1_4: main_scene_path + "spirit_1_4.png",
    spirit_1_5: main_scene_path + "spirit_1_5.png",

    spirit_1_skill: main_scene_path + "spirit_1_skill.png",

    spirit_side: main_scene_path + "spirit_side.png",

    spirit_face1: main_scene_path + "spirit_face1.png",
    spirit_face2: main_scene_path + "spirit_face2.png",
    spirit_face3: main_scene_path + "spirit_face3.png",


    progress1: main_scene_path + "progress1.png",
    progress2: main_scene_path + "progress2.png",
    progress3: main_scene_path + "progress3.png",
    progress4: main_scene_path + "progress4.png",
    progress5: main_scene_path + "progress5.png",
    progress6: main_scene_path + "progress6.png",
    progress7: main_scene_path + "progress7.png",
    progress8: main_scene_path + "progress8.png",
    progress9: main_scene_path + "progress9.png",
    progress10: main_scene_path + "progress10.png",
    progress11: main_scene_path + "progress11.png",
    progress12: main_scene_path + "progress12.png",
    progress13: main_scene_path + "progress13.png",

    vip1: main_scene_path + "vip1.png",
    vip2: main_scene_path + "vip2.png",
    vip3: main_scene_path + "vip3.png",
    vip4: main_scene_path + "vip4.png",
    vip5: main_scene_path + "vip5.png",
    vip6: main_scene_path + "vip6.png",
    vip7: main_scene_path + "vip7.png",
    vip8: main_scene_path + "vip8.png",
    vip9: main_scene_path + "vip9.png",
    vip10: main_scene_path + "vip10.png",
    vip11: main_scene_path + "vip11.png",
    vip12: main_scene_path + "vip12.png",

    num_red_0: main_scene_path + "num_red_0.png",
    num_red_1: main_scene_path + "num_red_1.png",
    num_red_2: main_scene_path + "num_red_2.png",
    num_red_3: main_scene_path + "num_red_3.png",
    num_red_4: main_scene_path + "num_red_4.png",
    num_red_5: main_scene_path + "num_red_5.png",
    num_red_6: main_scene_path + "num_red_6.png",
    num_red_7: main_scene_path + "num_red_7.png",
    num_red_8: main_scene_path + "num_red_8.png",
    num_red_9: main_scene_path + "num_red_9.png",

    edit: main_scene_path + "edit.png",
    edit1: main_scene_path + "edit1.png",
    edit2: main_scene_path + "edit2.png",
    edit3: main_scene_path + "edit3.png",

    card_frame_s: main_scene_path + "card_frame_s.png",
    card_frame1: main_scene_path + "card_frame1.png",
    card_frame2: main_scene_path + "card_frame2.png",
    card_frame3: main_scene_path + "card_frame3.png",
    card_frame4: main_scene_path + "card_frame4.png",
    card_frame5: main_scene_path + "card_frame5.png",

    card_icon0: main_scene_path + "card_icon0.png",
    card_icon1: main_scene_path + "card_icon1.png",
    card_icon2: main_scene_path + "card_icon2.png",
    card_icon3: main_scene_path + "card_icon3.png",

    card_item_bg_s: main_scene_path + "card_item_bg_s.png",
    card_item_bg1: main_scene_path + "card_item_bg1.png",
    card_item_bg2: main_scene_path + "card_item_bg2.png",
    card_item_bg3: main_scene_path + "card_item_bg3.png",
    card_item_bg4: main_scene_path + "card_item_bg4.png",
    card_item_bg5: main_scene_path + "card_item_bg5.png",
    card_item_bg6: main_scene_path + "card_item_bg6.png",
    card_item_bg6s: main_scene_path + "card_item_bg6s.png",

    button0: main_scene_path + "button0.png",
    button0s: main_scene_path + "button0s.png",
    button1: main_scene_path + "button1.png",
    button1s: main_scene_path + "button1s.png",
    button2: main_scene_path + "button2.png",
    button2s: main_scene_path + "button2s.png",
    button2d: main_scene_path + "button2d.png",
//    button3: main_scene_path + "button3.png",
//    button3s: main_scene_path + "button3s.png",
//    button4: main_scene_path + "button4.png",
//    button4s: main_scene_path + "button4s.png",
//    button5: main_scene_path + "button5.png",
//    button5s: main_scene_path + "button5s.png",
//    button6: main_scene_path + "button6.png",
//    button6s: main_scene_path + "button6s.png",
//    button7: main_scene_path + "button7.png",
//    button7s: main_scene_path + "button7s.png",
    button8: main_scene_path + "button8.png",
    button8s: main_scene_path + "button8s.png",
    button9: main_scene_path + "button9.png",
    button9s: main_scene_path + "button9s.png",
    button9d: main_scene_path + "button9d.png",
    button10: main_scene_path + "button10.png",
    button10s: main_scene_path + "button10s.png",
    button11: main_scene_path + "button11.png",
    button11s: main_scene_path + "button11s.png",
    button12: main_scene_path + "button12.png",
    button12s: main_scene_path + "button12s.png",
    button13: main_scene_path + "button13.png",
    button13s: main_scene_path + "button13s.png",
    button13d: main_scene_path + "button13d.png",
    button14: main_scene_path + "button14.png",
    button14s: main_scene_path + "button14s.png",
    button14d: main_scene_path + "button14d.png",
    button15: main_scene_path + "button15.png",
    button15s: main_scene_path + "button15s.png",
    button15d: main_scene_path + "button15d.png",
    button16: main_scene_path + "button16.png",
    button16s: main_scene_path + "button16s.png",
    button17: main_scene_path + "button17.png",
    button17s: main_scene_path + "button17s.png",
    button18: main_scene_path + "button18.png",
//    button18s: main_scene_path + "button18s.png",
    button19: main_scene_path + "button19.png",
    button19s: main_scene_path + "button19s.png",
    button20: main_scene_path + "button20.png",
    button20s: main_scene_path + "button20s.png",
    button20d: main_scene_path + "button20d.png",
    button21: main_scene_path + "button21.png",
    button21s: main_scene_path + "button21s.png",
    button22: main_scene_path + "button22.png",
    button22s: main_scene_path + "button22s.png",
    button22d: main_scene_path + "button22d.png",
    button23: main_scene_path + "button23.png",
    button23s: main_scene_path + "button23s.png",
    button23d: main_scene_path + "button23d.png",
    button24: main_scene_path + "button24.png",
    button24s: main_scene_path + "button24s.png",
    button25: main_scene_path + "button25.png",
    button25s: main_scene_path + "button25s.png",
    button25d: main_scene_path + "button25d.png",
//    button26: main_scene_path + "button26.png",
//    button26s: main_scene_path + "button26s.png",
//    button27: main_scene_path + "button27.png",
//    button27s: main_scene_path + "button27s.png",
//    button28: main_scene_path + "button28.png",
//    button28s: main_scene_path + "button28s.png",
//    button29: main_scene_path + "button29.png",
//    button29s: main_scene_path + "button29s.png",
    button30: main_scene_path + "button30.png",
    button31: main_scene_path + "button31.png",
    button32: main_scene_path + "button32.png",
    button33: main_scene_path + "button33.png",
    button34: main_scene_path + "button34.png",
//    button35: main_scene_path + "button35.png",
    button36: main_scene_path + "button36.png",
    button36s: main_scene_path + "button36s.png",
    button37: main_scene_path + "button37.png",
    button37s: main_scene_path + "button37s.png",
    button38: main_scene_path + "button38.png",
    button38s: main_scene_path + "button38s.png",
    button39: main_scene_path + "button39.png",
    button39s: main_scene_path + "button39s.png",
    button40: main_scene_path + "button40.png",
    button40s: main_scene_path + "button40s.png",
    button40d: main_scene_path + "button40d.png",
    button41: main_scene_path + "button41.png",
    button41s: main_scene_path + "button41s.png",
    button42: main_scene_path + "button42.png",
    button43: main_scene_path + "button43.png",
    button44: main_scene_path + "button44.png",
    button45: main_scene_path + "button45.png",
    button46: main_scene_path + "button46.png",
    button46s: main_scene_path + "button46s.png",
    button47: main_scene_path + "button47.png",
    button47s: main_scene_path + "button47s.png",
    button48: main_scene_path + "button48.png",
    button48s: main_scene_path + "button48s.png",
    button49: main_scene_path + "button49.png",
    button49s: main_scene_path + "button49s.png",
    button50: main_scene_path + "button50.png",
    button50s: main_scene_path + "button50s.png",
    button51: main_scene_path + "button51.png",
    button51s: main_scene_path + "button51s.png",
    button52: main_scene_path + "button52.png",
    button52s: main_scene_path + "button52s.png",
    button53: main_scene_path + "button53.png",
    button53s: main_scene_path + "button53s.png",
    button54: main_scene_path + "button54.png",
    button54s: main_scene_path + "button54s.png",
    button55: main_scene_path + "button55.png",
    button55s: main_scene_path + "button55s.png",
    button56: main_scene_path + "button56.png",
    button56s: main_scene_path + "button56s.png",
    button57: main_scene_path + "button57.png",
    button57s: main_scene_path + "button57s.png",
    button58: main_scene_path + "button58.png",
    button58s: main_scene_path + "button58s.png",
    button59: main_scene_path + "button59.png",
    button59s: main_scene_path + "button59s.png",
    button60: main_scene_path + "button60.png",
    button60s: main_scene_path + "button60s.png",
    button61: main_scene_path + "button61.png",
    button61s: main_scene_path + "button61s.png",

    icon1: main_scene_path + "icon1.png",
    icon2: main_scene_path + "icon2.png",
    icon3: main_scene_path + "icon3.png",
    icon4: main_scene_path + "icon4.png",
    icon5: main_scene_path + "icon5.png",
    icon6: main_scene_path + "icon6.png",
    icon7: main_scene_path + "icon7.png",
    icon8: main_scene_path + "icon8.png",
    icon9: main_scene_path + "icon9.png",
    icon10: main_scene_path + "icon10.png",
    icon11: main_scene_path + "icon11.png",
    icon12: main_scene_path + "icon12.png",
    icon13: main_scene_path + "icon13.png",
    icon14: main_scene_path + "icon14.png",
    icon15: main_scene_path + "icon15.png",
    icon16: main_scene_path + "icon16.png",
    icon17: main_scene_path + "icon17.png",
    icon18: main_scene_path + "icon18.png",
    icon19: main_scene_path + "icon19.png",
    icon20: main_scene_path + "icon20.png",
    icon21: main_scene_path + "icon21.png",
    icon22: main_scene_path + "icon22.png",
    icon23: main_scene_path + "icon23.png",
    icon24: main_scene_path + "icon24.png",
    icon25: main_scene_path + "icon25.png",
    icon26: main_scene_path + "icon26.png",
    icon27: main_scene_path + "icon27.png",
    icon28: main_scene_path + "icon28.png",
    icon29: main_scene_path + "icon29.png",
    icon30: main_scene_path + "icon30.png",
    icon31: main_scene_path + "icon31.png",
    icon32: main_scene_path + "icon32.png",
    icon33: main_scene_path + "icon33.png",
    icon34: main_scene_path + "icon34.png",
    icon35: main_scene_path + "icon35.png",
    icon36: main_scene_path + "icon36.png",
    icon37: main_scene_path + "icon37.png",
    icon38: main_scene_path + "icon38.png",
    icon39: main_scene_path + "icon39.png",
    icon40: main_scene_path + "icon40.png",
    icon41: main_scene_path + "icon41.png",
    icon42: main_scene_path + "icon42.png",
    icon43: main_scene_path + "icon43.png",
    icon44: main_scene_path + "icon44.png",
    icon45: main_scene_path + "icon45.png",
    icon46: main_scene_path + "icon46.png",
    icon47: main_scene_path + "icon47.png",
    icon48: main_scene_path + "icon48.png",
    icon49: main_scene_path + "icon49.png",
    icon50: main_scene_path + "icon50.png",
    icon51: main_scene_path + "icon51.png",
    icon52: main_scene_path + "icon52.png",
    icon53: main_scene_path + "icon53.png",
    icon54: main_scene_path + "icon54.png",
    icon55: main_scene_path + "icon55.png",
    icon56: main_scene_path + "icon56.png",
    icon57: main_scene_path + "icon57.png",
    icon58: main_scene_path + "icon58.png",
    icon59: main_scene_path + "icon59.png",
    icon60: main_scene_path + "icon60.png",
    icon61: main_scene_path + "icon61.png",
    icon62: main_scene_path + "icon62.png",
    icon63: main_scene_path + "icon63.png",
    icon64: main_scene_path + "icon64.png",
    icon65: main_scene_path + "icon65.png",
    icon66: main_scene_path + "icon66.png",
    icon67: main_scene_path + "icon67.png",
    icon68: main_scene_path + "icon68.png",
    icon69: main_scene_path + "icon69.png",
    icon70: main_scene_path + "icon70.png",
    icon71: main_scene_path + "icon71.png",
    icon72: main_scene_path + "icon72.png",
    icon73: main_scene_path + "icon73.png",
    icon74: main_scene_path + "icon74.png",
    icon75: main_scene_path + "icon75.png",
    icon76: main_scene_path + "icon76.png",
    icon77: main_scene_path + "icon77.png",
    icon78: main_scene_path + "icon78.png",
    icon79: main_scene_path + "icon79.png",
    icon80: main_scene_path + "icon80.png",
    icon81: main_scene_path + "icon81.png",
    icon82: main_scene_path + "icon82.png",
    icon83: main_scene_path + "icon83.png",
    icon84: main_scene_path + "icon84.png",
    icon85: main_scene_path + "icon85.png",
    icon86: main_scene_path + "icon86.png",
    icon87: main_scene_path + "icon87.png",
    icon88: main_scene_path + "icon88.png",
    icon89: main_scene_path + "icon89.png",
    icon90: main_scene_path + "icon90.png",
    icon91: main_scene_path + "icon91.png",
    icon92: main_scene_path + "icon92.png",
//    icon93: main_scene_path + "icon93.png",
    icon94: main_scene_path + "icon94.png",
//    icon95: main_scene_path + "icon95.png",
    icon96: main_scene_path + "icon96.png",
    icon97: main_scene_path + "icon97.png",
    icon98: main_scene_path + "icon98.png",
    icon99: main_scene_path + "icon99.png",
    icon100: main_scene_path + "icon100.png",
    icon103: main_scene_path + "icon103.png",
    icon104: main_scene_path + "icon104.png",
    icon105: main_scene_path + "icon105.png",
    icon106: main_scene_path + "icon106.png",
    icon107: main_scene_path + "icon107.png",
    icon108: main_scene_path + "icon108.png",
    icon109: main_scene_path + "icon109.png",
    icon110: main_scene_path + "icon110.png",
    icon111: main_scene_path + "icon111.png",
    icon112: main_scene_path + "icon112.png",
    icon113: main_scene_path + "icon113.png",
    icon114: main_scene_path + "icon114.png",
    icon115: main_scene_path + "icon115.png",
    icon116: main_scene_path + "icon116.png",
    icon117: main_scene_path + "icon117.png",
    icon118: main_scene_path + "icon118.png",
    icon119: main_scene_path + "icon119.png",
    icon120: main_scene_path + "icon120.png",
    icon121: main_scene_path + "icon121.png",
    icon122: main_scene_path + "icon122.png",
    icon123: main_scene_path + "icon123.png",
    icon124: main_scene_path + "icon124.png",
    icon125: main_scene_path + "icon125.png",
//    icon126: main_scene_path + "icon126.png",
    icon127: main_scene_path + "icon127.png",
    icon128: main_scene_path + "icon128.png",
    icon129: main_scene_path + "icon129.png",
    icon130: main_scene_path + "icon130.png",
    icon131: main_scene_path + "icon131.png",
//    icon132: main_scene_path + "icon132.png",
    icon133: main_scene_path + "icon133.png",
    icon134: main_scene_path + "icon134.png",
    icon135: main_scene_path + "icon135.png",
    icon136: main_scene_path + "icon136.png",
    icon137: main_scene_path + "icon137.png",
    icon138: main_scene_path + "icon138.png",
    icon139: main_scene_path + "icon139.png",
    icon140: main_scene_path + "icon140.png",
    icon141: main_scene_path + "icon141.png",
    icon142: main_scene_path + "icon142.png",
    icon143: main_scene_path + "icon143.png",
    icon144: main_scene_path + "icon144.png",
    icon145: main_scene_path + "icon145.png",
    icon146: main_scene_path + "icon146.png",
    icon147: main_scene_path + "icon147.png",
    icon148: main_scene_path + "icon148.png",
    icon149: main_scene_path + "icon149.png",
    icon150: main_scene_path + "icon150.png",
    icon151: main_scene_path + "icon151.png",
    icon152: main_scene_path + "icon152.png",
    icon153: main_scene_path + "icon153.png",
    icon154: main_scene_path + "icon154.png",
    icon155: main_scene_path + "icon155.png",
    icon156: main_scene_path + "icon156.png",
    icon157: main_scene_path + "icon157.png",
    icon158: main_scene_path + "icon158.png",
    icon159: main_scene_path + "icon159.png",
    icon160: main_scene_path + "icon160.png",
    icon161: main_scene_path + "icon161.png",
    icon162: main_scene_path + "icon162.png",
    icon163: main_scene_path + "icon163.png",
    icon164: main_scene_path + "icon164.png",
    icon165: main_scene_path + "icon165.png",
    icon166: main_scene_path + "icon166.png",
    icon167: main_scene_path + "icon167.png",
    icon168: main_scene_path + "icon168.png",
    icon169: main_scene_path + "icon169.png",
    icon170: main_scene_path + "icon170.png",
    icon171: main_scene_path + "icon171.png",
    icon172: main_scene_path + "icon172.png",
    icon173: main_scene_path + "icon173.png",
    icon174: main_scene_path + "icon174.png",
    icon175: main_scene_path + "icon175.png",
    icon176: main_scene_path + "icon176.png",
    icon177: main_scene_path + "icon177.png",
    icon178: main_scene_path + "icon178.png",
    icon179: main_scene_path + "icon179.png",
    icon180: main_scene_path + "icon180.png",
    icon181: main_scene_path + "icon181.png",
    icon182: main_scene_path + "icon182.png",
    icon183: main_scene_path + "icon183.png",
    icon184: main_scene_path + "icon184.png",
    icon185: main_scene_path + "icon185.png",
    icon186: main_scene_path + "icon186.png",
    icon187: main_scene_path + "icon187.png",
    icon188: main_scene_path + "icon188.png",
    icon189: main_scene_path + "icon189.png",
    icon190: main_scene_path + "icon190.png",
    icon191: main_scene_path + "icon191.png",
    icon192: main_scene_path + "icon192.png",
    icon193: main_scene_path + "icon193.png",
    icon194: main_scene_path + "icon194.png",
    icon195: main_scene_path + "icon195.png",
    icon196: main_scene_path + "icon196.png",
    icon197: main_scene_path + "icon197.png",
    icon198: main_scene_path + "icon198.png",
    icon199: main_scene_path + "icon199.png",
    icon200: main_scene_path + "icon200.png",
    icon201: main_scene_path + "icon201.png",
    icon202: main_scene_path + "icon202.png",
    icon203: main_scene_path + "icon203.png",
    icon204: main_scene_path + "icon204.png",
    icon205: main_scene_path + "icon205.png",
    icon206: main_scene_path + "icon206.png",
    icon207: main_scene_path + "icon207.png",
    icon208: main_scene_path + "icon208.png",
    icon209: main_scene_path + "icon209.png",
    icon210: main_scene_path + "icon210.png",
    icon211: main_scene_path + "icon211.png",
    icon212: main_scene_path + "icon212.png",
    icon213: main_scene_path + "icon213.png",
    icon214: main_scene_path + "icon214.png",
    icon215: main_scene_path + "icon215.png",
    icon216: main_scene_path + "icon216.png",
    icon217: main_scene_path + "icon217.png",
    icon218: main_scene_path + "icon218.png",
    icon219: main_scene_path + "icon219.png",
    icon220: main_scene_path + "icon220.png",
    icon221: main_scene_path + "icon221.png",
    icon222: main_scene_path + "icon222.png",
    icon223: main_scene_path + "icon223.png",
    icon224: main_scene_path + "icon224.png",
    icon225: main_scene_path + "icon225.png",
    icon226: main_scene_path + "icon226.png",
    icon227: main_scene_path + "icon227.png",
    icon228: main_scene_path + "icon228.png",
    icon229: main_scene_path + "icon229.png",
    icon230: main_scene_path + "icon230.png",
    icon231: main_scene_path + "icon231.png",
    icon232: main_scene_path + "icon232.png",
    icon233: main_scene_path + "icon233.png",
    icon234: main_scene_path + "icon234.png",
    icon235: main_scene_path + "icon235.png",
    icon236: main_scene_path + "icon236.png",
    icon237: main_scene_path + "icon237.png",
    icon238: main_scene_path + "icon238.png",
    icon239: main_scene_path + "icon239.png",
    icon240: main_scene_path + "icon240.png",
    icon241: main_scene_path + "icon241.png",
    icon242: main_scene_path + "icon242.png",
    icon243: main_scene_path + "icon243.png",
    icon244: main_scene_path + "icon244.png",
    icon245: main_scene_path + "icon245.png",
    icon246: main_scene_path + "icon246.png",
    icon247: main_scene_path + "icon247.png",
    icon248: main_scene_path + "icon248.png",
    icon249: main_scene_path + "icon249.png",
    icon250: main_scene_path + "icon250.png",
    icon251: main_scene_path + "icon251.png",
    icon252: main_scene_path + "icon252.png",
    icon253: main_scene_path + "icon253.png",
    icon254: main_scene_path + "icon254.png",
    icon255: main_scene_path + "icon255.png",
    icon256: main_scene_path + "icon256.png",
    icon257: main_scene_path + "icon257.png",
    icon258: main_scene_path + "icon258.png",
    icon259: main_scene_path + "icon259.png",
    icon260: main_scene_path + "icon260.png",
    icon261: main_scene_path + "icon261.png",
    icon262: main_scene_path + "icon262.png",
    icon263: main_scene_path + "icon263.png",
    icon264: main_scene_path + "icon264.png",
    icon265: main_scene_path + "icon265.png",
    icon266: main_scene_path + "icon266.png",
    icon267: main_scene_path + "icon267.png",
    icon268: main_scene_path + "icon268.png",
    icon269: main_scene_path + "icon269.png",
    icon270: main_scene_path + "icon270.png",
    icon271: main_scene_path + "icon271.png",
    icon272: main_scene_path + "icon272.png",
    icon273: main_scene_path + "icon273.png",
    icon274: main_scene_path + "icon274.png",
    icon275: main_scene_path + "icon275.png",
    icon276: main_scene_path + "icon276.png",
    icon277: main_scene_path + "icon277.png",
    icon278: main_scene_path + "icon278.png",
    icon279: main_scene_path + "icon279.png",
    icon280: main_scene_path + "icon280.png",
    icon281: main_scene_path + "icon281.png",
    icon282: main_scene_path + "icon282.png",
    icon283: main_scene_path + "icon283.png",
    icon284: main_scene_path + "icon284.png",
    icon285: main_scene_path + "icon285.png",
    icon286: main_scene_path + "icon286.png",
    icon287: main_scene_path + "icon287.png",
    icon288: main_scene_path + "icon288.png",
    icon289: main_scene_path + "icon289.png",
    icon290: main_scene_path + "icon290.png",
    icon291: main_scene_path + "icon291.png",

    card30000_head1: main_scene_path + "card30000_head1.png",
    card30000_half1: main_scene_path + "card30000_half1.png",
    card30000_full1: main_scene_path + "card30000_full1.png",

    // 特效
    battleNode: "res/ccb/battleNode.ccbi",
    spiritNode: "res/ccb/spiritNode.ccbi",
    tipNode: "res/ccb/tipNode.ccbi",

    TestTimelineCallback: "res/ccb/TestTimelineCallback.ccbi",
    effect1: "res/ccb/effect1.ccbi",
    effect2: "res/ccb/effect2.ccbi",
    effect3: "res/ccb/effect3.ccbi",
    effect4: "res/ccb/effect4.ccbi",
    effect5: "res/ccb/effect5.ccbi",
    effect6: "res/ccb/effect6.ccbi",
    effect7: "res/ccb/effect7.ccbi",
    effect8: "res/ccb/effect8.ccbi",
    effect9: "res/ccb/effect9.ccbi",
    effect10: "res/ccb/effect10.ccbi",
    effect11: "res/ccb/effect11.ccbi",
    effect12: "res/ccb/effect12.ccbi",
    effect13: "res/ccb/effect13.ccbi",
    effect14: "res/ccb/effect14.ccbi",
    effect15: "res/ccb/effect15.ccbi",

    uiEffect1: "res/ccb/uiEffect1.ccbi",
    uiEffect2: "res/ccb/uiEffect2.ccbi",
    uiEffect3: "res/ccb/uiEffect3.ccbi",
    uiEffect4: "res/ccb/uiEffect4.ccbi",
    uiEffect5: "res/ccb/uiEffect5.ccbi",
    uiEffect6: "res/ccb/uiEffect6.ccbi",
    uiEffect7: "res/ccb/uiEffect7.ccbi",
    uiEffect8: "res/ccb/uiEffect8.ccbi",
    uiEffect9: "res/ccb/uiEffect9.ccbi",
    uiEffect10: "res/ccb/uiEffect10.ccbi",
    uiEffect11: "res/ccb/uiEffect11.ccbi",
    uiEffect12: "res/ccb/uiEffect12.ccbi",
    uiEffect13: "res/ccb/uiEffect13.ccbi",
    uiEffect14: "res/ccb/uiEffect14.ccbi",
    uiEffect15: "res/ccb/uiEffect15.ccbi",
    uiEffect16: "res/ccb/uiEffect16.ccbi",
    uiEffect17: "res/ccb/uiEffect17.ccbi",
    uiEffect18: "res/ccb/uiEffect18.ccbi",
    uiEffect19: "res/ccb/uiEffect19.ccbi",
    uiEffect20: "res/ccb/uiEffect20.ccbi",
    uiEffect21: "res/ccb/uiEffect21.ccbi",
    uiEffect22: "res/ccb/uiEffect22.ccbi",
    uiEffect23: "res/ccb/uiEffect23.ccbi",
    uiEffect24: "res/ccb/uiEffect24.ccbi",
    uiEffect25: "res/ccb/uiEffect25.ccbi",
    uiEffect26: "res/ccb/uiEffect26.ccbi",
    uiEffect27: "res/ccb/uiEffect27.ccbi",
    uiEffect28: "res/ccb/uiEffect28.ccbi",
    uiEffect29: "res/ccb/uiEffect29.ccbi",
    uiEffect30: "res/ccb/uiEffect30.ccbi",
    uiEffect31: "res/ccb/uiEffect31.ccbi",
    uiEffect32: "res/ccb/uiEffect32.ccbi",
    uiEffect33: "res/ccb/uiEffect33.ccbi",
    uiEffect34: "res/ccb/uiEffect34.ccbi",
    uiEffect35: "res/ccb/uiEffect35.ccbi",
    uiEffect36: "res/ccb/uiEffect36.ccbi",
    uiEffect37: "res/ccb/uiEffect37.ccbi",
    uiEffect38: "res/ccb/uiEffect38.ccbi",
    uiEffect39: "res/ccb/uiEffect39.ccbi",
    uiEffect40: "res/ccb/uiEffect40.ccbi",
//    uiEffect41: "res/ccb/uiEffect41.ccbi",
//    uiEffect42: "res/ccb/uiEffect42.ccbi",
//    uiEffect43: "res/ccb/uiEffect43.ccbi",
//    uiEffect44: "res/ccb/uiEffect44.ccbi",
//    uiEffect45: "res/ccb/uiEffect45.ccbi",
//    uiEffect46: "res/ccb/uiEffect46.ccbi",
//    uiEffect47: "res/ccb/uiEffect47.ccbi",
//    uiEffect48: "res/ccb/uiEffect48.ccbi",
//    uiEffect49: "res/ccb/uiEffect49.ccbi",
//    uiEffect50: "res/ccb/uiEffect50.ccbi",
//    uiEffect51: "res/ccb/uiEffect51.ccbi",
//    uiEffect52: "res/ccb/uiEffect52.ccbi",
//    uiEffect53: "res/ccb/uiEffect53.ccbi",
//    uiEffect54: "res/ccb/uiEffect54.ccbi",
//    uiEffect55: "res/ccb/uiEffect55.ccbi",
//    uiEffect56: "res/ccb/uiEffect56.ccbi",
//    uiEffect57: "res/ccb/uiEffect57.ccbi",
//    uiEffect58: "res/ccb/uiEffect58.ccbi",
//    uiEffect59: "res/ccb/uiEffect59.ccbi",
//    uiEffect60: "res/ccb/uiEffect60.ccbi",
//    uiEffect61: "res/ccb/uiEffect61.ccbi",
//    uiEffect62: "res/ccb/uiEffect62.ccbi",
//    uiEffect63: "res/ccb/uiEffect63.ccbi",
//    uiEffect64: "res/ccb/uiEffect64.ccbi",
//    uiEffect65: "res/ccb/uiEffect65.ccbi",
//    uiEffect66: "res/ccb/uiEffect66.ccbi",
//    uiEffect67: "res/ccb/uiEffect67.ccbi",
//    uiEffect68: "res/ccb/uiEffect68.ccbi",
//    uiEffect69: "res/ccb/uiEffect69.ccbi",
//    uiEffect70: "res/ccb/uiEffect70.ccbi",
//    uiEffect71: "res/ccb/uiEffect71.ccbi",
//    uiEffect72: "res/ccb/uiEffect72.ccbi",
//    uiEffect73: "res/ccb/uiEffect73.ccbi",


    // 特效资源
    p1: "res/effect/effect/p1.png",
    p2: "res/effect/effect/p2.png",
    p3: "res/effect/effect/p3.png",
    p4: "res/effect/effect/p4.png",
    p5: "res/effect/effect/p5.png",
    p6: "res/effect/effect/p6.png",
    p7: "res/effect/effect/p7.png",
    p8: "res/effect/effect/p8.png",
    p9: "res/effect/effect/p9.png",
    p10: "res/effect/effect/p10.png",
    p11: "res/effect/effect/p11.png",
    p12: "res/effect/effect/p12.png",
    p13: "res/effect/effect/p13.png",
    p14: "res/effect/effect/p14.png",
    p15: "res/effect/effect/p15.png",
    p16: "res/effect/effect/p16.png",
    p17: "res/effect/effect/p17.png",
    p18: "res/effect/effect/p18.png",
    p19: "res/effect/effect/p19.png",
    p20: "res/effect/effect/p20.png",
    p21: "res/effect/effect/p21.png",
    p22: "res/effect/effect/p22.png",
    p23: "res/effect/effect/p23.png",
    p24: "res/effect/effect/p24.png",
    p25: "res/effect/effect/p25.png",
    p26: "res/effect/effect/p26.png",
    p27: "res/effect/effect/p27.png",
    p28: "res/effect/effect/p28.png",
    p29: "res/effect/effect/p29.png",
    p30: "res/effect/effect/p30.png",
    p31: "res/effect/effect/p31.png",
    p32: "res/effect/effect/p32.png",
    p33: "res/effect/effect/p33.png",

    up1: "res/effect/uiEffect/up1.png",
    up2: "res/effect/uiEffect/up2.png",
    up3: "res/effect/uiEffect/up3.png",
    up4: "res/effect/uiEffect/up4.png",
    up5: "res/effect/uiEffect/up5.png",
    up6: "res/effect/uiEffect/up6.png",
    up7: "res/effect/uiEffect/up7.png",
    up8: "res/effect/uiEffect/up8.png",
    up9: "res/effect/uiEffect/up9.png",
    up10: "res/effect/uiEffect/up10.png",
    up11: "res/effect/uiEffect/up11.png",
    up12: "res/effect/uiEffect/up12.png",
    up13: "res/effect/uiEffect/up13.png",
    up14: "res/effect/uiEffect/up14.png",
    up15: "res/effect/uiEffect/up15.png",
    up16: "res/effect/uiEffect/up16.png",
    up17: "res/effect/uiEffect/up17.png",
    up18: "res/effect/uiEffect/up18.png",
    up19: "res/effect/uiEffect/up19.png",
    up20: "res/effect/uiEffect/up20.png",
    up21: "res/effect/uiEffect/up21.png",
    up22: "res/effect/uiEffect/up22.png",
    up23: "res/effect/uiEffect/up23.png",
    up24: "res/effect/uiEffect/up24.png",
    up25: "res/effect/uiEffect/up25.png",
    up26: "res/effect/uiEffect/up26.png",
    up27: "res/effect/uiEffect/up27.png",
    up28: "res/effect/uiEffect/up28.png",
    up29: "res/effect/uiEffect/up29.png",
    up30: "res/effect/uiEffect/up30.png",
    up31: "res/effect/uiEffect/up31.png",
//    up32: "res/effect/uiEffect/up32.png",
//    up33: "res/effect/uiEffect/up33.png",
    up34: "res/effect/uiEffect/up34.png",
    up35: "res/effect/uiEffect/up35.png",
    up36: "res/effect/uiEffect/up36.png",
    up37: "res/effect/uiEffect/up37.png",
    up38: "res/effect/uiEffect/up38.png",
    up39: "res/effect/uiEffect/up39.png",
    up40: "res/effect/uiEffect/up40.png",
    up41: "res/effect/uiEffect/up41.png",
    up42: "res/effect/uiEffect/up42.png",
    up43: "res/effect/uiEffect/up43.png",
    up44: "res/effect/uiEffect/up44.png",
    up45: "res/effect/uiEffect/up45.png",
    up46: "res/effect/uiEffect/up46.png",
    up47: "res/effect/uiEffect/up47.png",
    up48: "res/effect/uiEffect/up48.png",
    up49: "res/effect/uiEffect/up49.png",
    up50: "res/effect/uiEffect/up50.png",
    up51: "res/effect/uiEffect/up51.png",
    up52: "res/effect/uiEffect/up52.png",
    up53: "res/effect/uiEffect/up53.png",
    up54: "res/effect/uiEffect/up54.png",
    up55: "res/effect/uiEffect/up55.png",
    up56: "res/effect/uiEffect/up56.png",
    up57: "res/effect/uiEffect/up57.png",
    up58: "res/effect/uiEffect/up58.png",
    up59: "res/effect/uiEffect/up59.png",
    up60: "res/effect/uiEffect/up60.png",
    up61: "res/effect/uiEffect/up61.png",
    up62: "res/effect/uiEffect/up62.png",
    up63: "res/effect/uiEffect/up63.png",
    up64: "res/effect/uiEffect/up64.png",
    up65: "res/effect/uiEffect/up65.png",
    up66: "res/effect/uiEffect/up66.png",
    up67: "res/effect/uiEffect/up67.png",
    up68: "res/effect/uiEffect/up68.png",
    up69: "res/effect/uiEffect/up69.png",
    up70: "res/effect/uiEffect/up70.png",
    up71: "res/effect/uiEffect/up71.png",
    up72: "res/effect/uiEffect/up72.png",
    up73: "res/effect/uiEffect/up73.png",
    up74: "res/effect/uiEffect/up74.png",
    up75: "res/effect/uiEffect/up75.png",
    up76: "res/effect/uiEffect/up76.png",
    up77: "res/effect/uiEffect/up77.png",
    up78: "res/effect/uiEffect/up78.png",
    up79: "res/effect/uiEffect/up79.png",
    up80: "res/effect/uiEffect/up80.png",
    up81: "res/effect/uiEffect/up81.png",
    up82: "res/effect/uiEffect/up82.png",
    up83: "res/effect/uiEffect/up83.png",
    up84: "res/effect/uiEffect/up84.png",
    up85: "res/effect/uiEffect/up85.png",
    up86: "res/effect/uiEffect/up86.png",
    up87: "res/effect/uiEffect/up87.png",
    up88: "res/effect/uiEffect/up88.png",
    up89: "res/effect/uiEffect/up89.png",
    up90: "res/effect/uiEffect/up90.png",
    up91: "res/effect/uiEffect/up91.png",
    up92: "res/effect/uiEffect/up92.png",
    up93: "res/effect/uiEffect/up93.png",
   // up94: "res/effect/uiEffect/up94.png",
    up95: "res/effect/uiEffect/up95.png",
    up96: "res/effect/uiEffect/up96.png",
    up97: "res/effect/uiEffect/up97.png",
    up98: "res/effect/uiEffect/up98.png",
    up99: "res/effect/uiEffect/up99.png",
    up100: "res/effect/uiEffect/up100.png",
    up101: "res/effect/uiEffect/up101.png",
    up102: "res/effect/uiEffect/up102.png",
    up103: "res/effect/uiEffect/up103.png",
    up104: "res/effect/uiEffect/up104.png",



    // 新手特效
    tutorials1: "res/ccb/tutorials1.ccbi",
    tutorials2: "res/ccb/tutorials2.ccbi",
    tutorials3: "res/ccb/tutorials3.ccbi",
    tutorials4: "res/ccb/tutorials4.ccbi",
    tutorials5: "res/ccb/tutorials5.ccbi",
    tutorials6: "res/ccb/tutorials6.ccbi",
    tutorials7: "res/ccb/tutorials7.ccbi",
    tutorials8: "res/ccb/tutorials8.ccbi",
    tutorials9: "res/ccb/tutorials9.ccbi",
    tutorials10: "res/ccb/tutorials10.ccbi",
    tutorials11: "res/ccb/tutorials11.ccbi",
    tutorials12: "res/ccb/tutorials12.ccbi",
    tutorials13: "res/ccb/tutorials13.ccbi",
    tutorials14: "res/ccb/tutorials14.ccbi",
    tutorials15: "res/ccb/tutorials15.ccbi",
    tutorials16: "res/ccb/tutorials16.ccbi",

    // 新手特效资源
    empty: "res/effect/NewPlayer/empty.png",
    hand: "res/effect/NewPlayer/hand.png",
    light: "res/effect/NewPlayer/light.png",
    talking: "res/effect/NewPlayer/talking.png",
    yuanshen: "res/effect/NewPlayer/yuanshen.png",

    main_bg_music: "res/sound/main_bg_music.mp3",
    battle_bg_music: "res/sound/battle_bg_music.mp3",
    battle_sound_aoe: "res/sound/battle_sound_aoe.wav",
    battle_sound_atk: "res/sound/battle_sound_atk.wav",
    battle_sound_buff: "res/sound/battle_sound_buff.wav",
    battle_sound_heal: "res/sound/battle_sound_heal.wav",
    battle_sound_lose: "res/sound/battle_sound_lose.wav",
    battle_sound_miss: "res/sound/battle_sound_miss.wav",
    battle_sound_single: "res/sound/battle_sound_single.wav",
    battle_sound_subtitle_card: "res/sound/battle_sound_subtitle_card.wav",
    battle_sound_subtitle_spirit: "res/sound/battle_sound_subtitle_spirit.wav",
    battle_sound_win: "res/sound/battle_sound_win.wav",
    card_upgrade_sound: "res/sound/card_upgrade_sound.wav",
    click_building_sound: "res/sound/click_building_sound.wav",
    click_gold_sound: "res/sound/click_gold_sound.wav",
    highlights_sound: "res/sound/highlights_sound.wav",
    click_button_sound: "res/sound/click_button_sound.wav",
    player_upgrade_sound: "res/sound/player_upgrade_sound.wav",
    spirit_upgrade_sound: "res/sound/spirit_upgrade_sound.wav",
    star_sound: "res/sound/star_sound.wav"
};

var main_scene_res = [
    //image
    //plist
    //fnt
    //tmx
    //bgm
    //effect
];

for (var cardId = 1; cardId <= 6; ++cardId) {
    main_scene_image["card" + cardId + "_head1"] = main_scene_path + "card" + cardId + "_head1.png";
    main_scene_image["card" + cardId + "_head2"] = main_scene_path + "card" + cardId + "_head2.png";
    main_scene_image["card" + cardId + "_head3"] = main_scene_path + "card" + cardId + "_head3.png";

    main_scene_image["card" + cardId + "_half1"] = main_scene_path + "card" + cardId + "_half1.png";
    main_scene_image["card" + cardId + "_half2"] = main_scene_path + "card" + cardId + "_half2.png";
    main_scene_image["card" + cardId + "_half3"] = main_scene_path + "card" + cardId + "_half3.png";

    main_scene_image["card" + cardId + "_full1"] = main_scene_path + "card" + cardId + "_full1.png";
    main_scene_image["card" + cardId + "_full2"] = main_scene_path + "card" + cardId + "_full2.png";
    main_scene_image["card" + cardId + "_full3"] = main_scene_path + "card" + cardId + "_full3.png";
}

for (var cardId = 10000; cardId <= 10032; ++cardId) {
    main_scene_image["card" + cardId + "_half1"] = main_scene_path + "card" + cardId + "_half1.png";
}

for (var taskId = 1; taskId <= 50; ++taskId) {
    main_scene_image["task" + taskId] = main_scene_path + "task" + taskId + ".png";
}

var effectConfig = [
    10,
    10,
    10,
    5,
    6,
    7,
    6,
    8,
    6,
    12,
    8,
    4,
    4
];

var effectRect = [
    cc.rect(0, 0, 160, 80),
    cc.rect(0, 0, 132, 132),
    cc.rect(0, 0, 640, 218),
    cc.rect(0, 0, 600, 713),
    cc.rect(0, 0, 120, 275),
    cc.rect(0, 0, 182, 171),
    cc.rect(0, 0, 250, 275),
    cc.rect(0, 0, 83, 261),
    cc.rect(0, 0, 251, 279),
    cc.rect(0, 0, 188, 263),
    cc.rect(0, 0, 464, 391),
    cc.rect(0, 0, 280, 308),
    cc.rect(0, 0, 170, 185)
];

for (var effectId = 0; effectId < effectConfig.length; ++effectId) {
    for (var frameI = 0; frameI < effectConfig[effectId]; ++frameI) {
        main_scene_image["effect" + effectId + "_frame" + frameI] = "res/effect/" + effectId + "/" + frameI + ".png";
    }
}

for (var key in main_scene_image) {
    main_scene_res.push({src: main_scene_image[key]});
}

//字体
main_scene_res.push({src: "./res/font/skillName.fnt"});
main_scene_res.push({src: "./res/font/skillName.png"});
main_scene_res.push({src: "./res/font/tipNumber.fnt"});
main_scene_res.push({src: "./res/font/tipNumber.png"});

// battle scene res
var battle_scene_res = [
    //image

    //plist

    //fnt

    //tmx

    //bgm

    //effect
];