// Generated by CoffeeScript 1.6.3
(function() {
  var User;

  User = (function() {
    function User(opts) {
      this.id = opts.id;
      this.account = opts.account;
      this.name = opts.name;
      this.from = opts.last_login_device || '';
      this.password = opts.password;
      this.loginCount = opts.login_count;
      this.lastLoginTime = opts.last_login_time;
    }

    return User;

  })();

  module.exports = User;

}).call(this);
