// Generated by CoffeeScript 1.6.3
var dao;

dao = require('../../app/dao');

describe("Dao Factory", function() {
  return it("should can be init with specific 'mysql' type", function() {
    var _dao;
    _dao = dao.init('mysql');
    _dao.should.be.a('object');
    return _dao.should.be.equal(dao);
  });
});
