// Generated by CoffeeScript 1.6.3
var Area, eventManager, players, timer;

eventManager = require('../event/eventManager');

players = require('../../manager/playerCache');

timer = require('./timer');

Area = module.exports;

Area.init = function(opts) {
  return timer.run();
};

Area.addPlayer = function(player) {
  eventManager.addEventToPlayer(player);
  return players.put(player);
};

Area.removePlayer = function(playerId) {
  return players.del(playerId);
};

Area.getPlayer = function(playerId) {
  return players.get(playerId);
};

Area.getPlayers = function() {
  return players.all();
};

Area.powerConsume = function() {
  var p, _i, _len, _ref;
  _ref = this.getPlayers();
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    p = _ref[_i];
    p.emit('power.consume');
    p.emit('power.give');
  }
};
