// Generated by CoffeeScript 1.6.3
var Timer, area, count, tick;

area = require('./area');

Timer = module.exports;

Timer.run = function() {
  return setInterval(tick, 1000);
};

count = 1;

tick = function() {
  return area.powerConsume();
};
