var SETTING_IS_BROWSER = false;
if (typeof(navigator) != 'undefined') {
    SETTING_IS_BROWSER = true;
}

// main scene res
var main_scene_path = "../res/main/";
var effect_scene_path = "../res/effect/";
var ccb_scene_path = "../res/ccb/";
var test_scene_path = "../res/test/";


var main_scene_image = {
    bg1: main_scene_path + "bg1.png",
    // bg2: main_scene_path + "bg2.png",
    // bg3: main_scene_path + "bg3.png",
    // bg4: main_scene_path + "bg4.png",
    bg5: main_scene_path + "bg5.png",
    // bg6: main_scene_path + "bg6.png",
    // bg7: main_scene_path + "bg7.png",
    bg8: main_scene_path + "bg8.png",
    bg9: main_scene_path + "bg9.png",
    bg10: main_scene_path + "bg10.png",
    bg11: main_scene_path + "bg11.png",
    // bg12: main_scene_path + "bg12.png",
    bg13: main_scene_path + "bg13.png",
//    bg14: main_scene_path + "bg14.png",
    bg15: main_scene_path + "bg15.png",
    bg16: main_scene_path + "bg16.png",
    bg17: main_scene_path + "bg17.png",
    bg18: main_scene_path + "bg18.png",
    bg19: main_scene_path + "bg19.png",

   
    lv_bg: main_scene_path + "lv_bg.png",
    exp_bg: main_scene_path + "exp_bg.png",
    exp: main_scene_path + "exp.png",
    main_message_bg: main_scene_path + "main_message_bg.png",
    star1: main_scene_path + "star1.png",
    star2: main_scene_path + "star2.png",
    star3: main_scene_path + "star3.png",
    ladder1: main_scene_path + "ladder1.png",
    ladder2: main_scene_path + "ladder2.png",
    cloud: main_scene_path + "cloud.png",
    gameFrame: main_scene_path + "gameFrame.png",

   

    spirit_1_0: main_scene_path + "spirit_1_0.png",
    spirit_1_1: main_scene_path + "spirit_1_1.png",
    spirit_1_2: main_scene_path + "spirit_1_2.png",
    spirit_1_3: main_scene_path + "spirit_1_3.png",
    spirit_1_4: main_scene_path + "spirit_1_4.png",
    spirit_1_5: main_scene_path + "spirit_1_5.png",

    spirit_1_skill: main_scene_path + "spirit_1_skill.png",
    
    spirit_side: main_scene_path + "spirit_side.png",

    spirit_face1: main_scene_path + "spirit_face1.png",
    spirit_face2: main_scene_path + "spirit_face2.png",
    spirit_face3: main_scene_path + "spirit_face3.png",


    // progress1: main_scene_path + "progress1.png",
    // progress2: main_scene_path + "progress2.png",
    // progress3: main_scene_path + "progress3.png",
    // progress4: main_scene_path + "progress4.png",
    // progress5: main_scene_path + "progress5.png",
    // progress6: main_scene_path + "progress6.png",
    // progress7: main_scene_path + "progress7.png",
    // progress8: main_scene_path + "progress8.png",
    // progress9: main_scene_path + "progress9.png",
    // progress10: main_scene_path + "progress10.png",
    // progress11: main_scene_path + "progress11.png",
    // progress12: main_scene_path + "progress12.png",

    vip1: main_scene_path + "vip1.png",
    vip2: main_scene_path + "vip2.png",
    vip3: main_scene_path + "vip3.png",
    vip4: main_scene_path + "vip4.png",
    vip5: main_scene_path + "vip5.png",
    vip6: main_scene_path + "vip6.png",
    vip7: main_scene_path + "vip7.png",
    vip8: main_scene_path + "vip8.png",
    vip9: main_scene_path + "vip9.png",
    vip10: main_scene_path + "vip10.png",
    vip11: main_scene_path + "vip11.png",
    vip12: main_scene_path + "vip12.png",

    // pve_bg1: main_scene_path + "pve_bg1.png",
    // pvp_bg1: main_scene_path + "pvp_bg1.png",

    edit1: main_scene_path + "edit1.png",
    edit2: main_scene_path + "edit2.png",
    edit3: main_scene_path + "edit3.png",

    card_frame_s: main_scene_path + "card_frame_s.png",
    card_frame1: main_scene_path + "card_frame1.png",
    card_frame2: main_scene_path + "card_frame2.png",
    card_frame3: main_scene_path + "card_frame3.png",
    card_frame4: main_scene_path + "card_frame4.png",
    card_frame5: main_scene_path + "card_frame5.png",

    // card_icon1: main_scene_path + "card_icon1.png",
    // card_icon2: main_scene_path + "card_icon2.png",
    // card_icon3: main_scene_path + "card_icon3.png",

    card_item_bg_s: main_scene_path + "card_item_bg_s.png",
    card_item_bg1: main_scene_path + "card_item_bg1.png",
    card_item_bg2: main_scene_path + "card_item_bg2.png",
    card_item_bg3: main_scene_path + "card_item_bg3.png",
    card_item_bg4: main_scene_path + "card_item_bg4.png",
    card_item_bg5: main_scene_path + "card_item_bg5.png",

    // card_item_frame: main_scene_path + "card_item_frame.png",

    // button1: main_scene_path + "button1.png",
    // button1s: main_scene_path + "button1s.png",
    // button2: main_scene_path + "button2.png",
    // button2s: main_scene_path + "button2s.png",
    // button2d: main_scene_path + "button2d.png",
//    button3: main_scene_path + "button3.png",
//    button3s: main_scene_path + "button3s.png",
//    button4: main_scene_path + "button4.png",
//    button4s: main_scene_path + "button4s.png",
//    button5: main_scene_path + "button5.png",
//    button5s: main_scene_path + "button5s.png",
//    button6: main_scene_path + "button6.png",
//    button6s: main_scene_path + "button6s.png",
//    button7: main_scene_path + "button7.png",
//    button7s: main_scene_path + "button7s.png",
    // button8: main_scene_path + "button8.png",
    // button8s: main_scene_path + "button8s.png",
    button9: main_scene_path + "button9.png",
    button9s: main_scene_path + "button9s.png",
    button9d: main_scene_path + "button9d.png",
    // button10: main_scene_path + "button10.png",
    // button10s: main_scene_path + "button10s.png",
    // button11: main_scene_path + "button11.png",
    // button11s: main_scene_path + "button11s.png",
//    button12: main_scene_path + "button12.png",
//    button12s: main_scene_path + "button12s.png",
//    button12d: main_scene_path + "button12d.png",
//     button13: main_scene_path + "button13.png",
//     button13s: main_scene_path + "button13s.png",
//     button13d: main_scene_path + "button13d.png",
//     button14: main_scene_path + "button14.png",
//     button14s: main_scene_path + "button14s.png",
//     button14d: main_scene_path + "button14d.png",
//     button15: main_scene_path + "button15.png",
//     button15s: main_scene_path + "button15s.png",
//     button15d: main_scene_path + "button15d.png",
//     button16: main_scene_path + "button16.png",
//     button16s: main_scene_path + "button16s.png",
// //    button17: main_scene_path + "button17.png",
// //    button17s: main_scene_path + "button17s.png",
// //    button18: main_scene_path + "button18.png",
// //    button18s: main_scene_path + "button18s.png",
//     button19: main_scene_path + "button19.png",
//     button19s: main_scene_path + "button19s.png",
//     button20: main_scene_path + "button20.png",
//     button20s: main_scene_path + "button20s.png",
//     button20d: main_scene_path + "button20d.png",
//     button21: main_scene_path + "button21.png",
//     button21s: main_scene_path + "button21s.png",
//     button22: main_scene_path + "button22.png",
//     button22s: main_scene_path + "button22s.png",
//     button22d: main_scene_path + "button22d.png",
//     button23: main_scene_path + "button23.png",
//     button23s: main_scene_path + "button23s.png",
//     button23d: main_scene_path + "button23d.png",
//     button24: main_scene_path + "button24.png",
//     button24s: main_scene_path + "button24s.png",
//     button25: main_scene_path + "button25.png",
//     button25s: main_scene_path + "button25s.png",
//     button25d: main_scene_path + "button25d.png",
// //    button26: main_scene_path + "button26.png",
// //    button26s: main_scene_path + "button26s.png",
// //    button27: main_scene_path + "button27.png",
// //    button27s: main_scene_path + "button27s.png",
// //    button28: main_scene_path + "button28.png",
// //    button28s: main_scene_path + "button28s.png",
// //    button29: main_scene_path + "button29.png",
// //    button29s: main_scene_path + "button29s.png",
//     button30: main_scene_path + "button30.png",
//     button31: main_scene_path + "button31.png",
//     button32: main_scene_path + "button32.png",
//     button33: main_scene_path + "button33.png",
//     button34: main_scene_path + "button34.png",
// //    button35: main_scene_path + "button35.png",
//     button36: main_scene_path + "button36.png",
//     button36s: main_scene_path + "button36s.png",
//     button37: main_scene_path + "button37.png",
//     button37s: main_scene_path + "button37s.png",
//     button38: main_scene_path + "button38.png",
//     button38s: main_scene_path + "button38s.png",
//     button39: main_scene_path + "button39.png",
//     button39s: main_scene_path + "button39s.png",
//     button40: main_scene_path + "button40.png",
//     button40s: main_scene_path + "button40s.png",
//     button40d: main_scene_path + "button40d.png",
//     button41: main_scene_path + "button41.png",
//     button41s: main_scene_path + "button41s.png",
//     button42: main_scene_path + "button42.png",
//     button43: main_scene_path + "button43.png",
//     button44: main_scene_path + "button44.png",
//     button45: main_scene_path + "button45.png",
//     button46: main_scene_path + "button46.png",
//     button46s: main_scene_path + "button46s.png",
//     button47: main_scene_path + "button47.png",
//     button47s: main_scene_path + "button47s.png",
//     button48: main_scene_path + "button48.png",
//     button48s: main_scene_path + "button48s.png",
//     button49: main_scene_path + "button49.png",
//     button49s: main_scene_path + "button49s.png",
//     button50: main_scene_path + "button50.png",
//     button50s: main_scene_path + "button50s.png",
//     button51: main_scene_path + "button51.png",
//     button51s: main_scene_path + "button51s.png",
//     button52: main_scene_path + "button52.png",
//     button52s: main_scene_path + "button52s.png",
//     button53: main_scene_path + "button53.png",
//     button53s: main_scene_path + "button53s.png",
//     button54: main_scene_path + "button54.png",
//     button54s: main_scene_path + "button54s.png",
//     button55: main_scene_path + "button55.png",
//     button55s: main_scene_path + "button55s.png",
//     button56: main_scene_path + "button56.png",
//     button56s: main_scene_path + "button56s.png",
//     button57: main_scene_path + "button57.png",
//     button57s: main_scene_path + "button57s.png",
//     button58: main_scene_path + "button58.png",
//     button58s: main_scene_path + "button58s.png",
//     button59: main_scene_path + "button59.png",
//     button59s: main_scene_path + "button59s.png",
//     button60: main_scene_path + "button60.png",
//     button60s: main_scene_path + "button60s.png",


//     icon1: main_scene_path + "icon1.png",
//     icon2: main_scene_path + "icon2.png",
//     icon3: main_scene_path + "icon3.png",
//     icon4: main_scene_path + "icon4.png",
//     icon5: main_scene_path + "icon5.png",
//     icon6: main_scene_path + "icon6.png",
//     icon7: main_scene_path + "icon7.png",
//     icon8: main_scene_path + "icon8.png",
//     icon9: main_scene_path + "icon9.png",
//     icon10: main_scene_path + "icon10.png",
//     icon11: main_scene_path + "icon11.png",
//     icon12: main_scene_path + "icon12.png",
//     icon13: main_scene_path + "icon13.png",
//     icon14: main_scene_path + "icon14.png",
//     icon15: main_scene_path + "icon15.png",
//     icon16: main_scene_path + "icon16.png",
//     icon17: main_scene_path + "icon17.png",
//     icon18: main_scene_path + "icon18.png",
//     icon19: main_scene_path + "icon19.png",
//     icon20: main_scene_path + "icon20.png",
//     icon21: main_scene_path + "icon21.png",
//     icon22: main_scene_path + "icon22.png",
//     icon23: main_scene_path + "icon23.png",
//     icon24: main_scene_path + "icon24.png",
//     icon25: main_scene_path + "icon25.png",
//     icon26: main_scene_path + "icon26.png",
//     icon27: main_scene_path + "icon27.png",
//     icon28: main_scene_path + "icon28.png",
//     icon29: main_scene_path + "icon29.png",
//     icon30: main_scene_path + "icon30.png",
//     icon31: main_scene_path + "icon31.png",
//     icon32: main_scene_path + "icon32.png",
//     icon33: main_scene_path + "icon33.png",
//     icon34: main_scene_path + "icon34.png",
//     icon35: main_scene_path + "icon35.png",
//     icon36: main_scene_path + "icon36.png",
//     icon37: main_scene_path + "icon37.png",
//     icon38: main_scene_path + "icon38.png",
//     icon39: main_scene_path + "icon39.png",
//     icon40: main_scene_path + "icon40.png",
//     icon41: main_scene_path + "icon41.png",
// //    icon42: main_scene_path + "icon42.png",
//     icon43: main_scene_path + "icon43.png",
//     icon44: main_scene_path + "icon44.png",
//     icon45: main_scene_path + "icon45.png",
//     icon46: main_scene_path + "icon46.png",
//     icon47: main_scene_path + "icon47.png",
//     icon48: main_scene_path + "icon48.png",
//     icon49: main_scene_path + "icon49.png",
//     icon50: main_scene_path + "icon50.png",
//     icon51: main_scene_path + "icon51.png",
//     icon52: main_scene_path + "icon52.png",
//     icon53: main_scene_path + "icon53.png",
//     icon54: main_scene_path + "icon54.png",
//     icon55: main_scene_path + "icon55.png",
//     icon56: main_scene_path + "icon56.png",
//     icon57: main_scene_path + "icon57.png",
//     icon58: main_scene_path + "icon58.png",
//     icon59: main_scene_path + "icon59.png",
//     icon60: main_scene_path + "icon60.png",
//     icon61: main_scene_path + "icon61.png",
//     icon62: main_scene_path + "icon62.png",
//     icon63: main_scene_path + "icon63.png",
//     icon64: main_scene_path + "icon64.png",
//     icon65: main_scene_path + "icon65.png",
//     icon66: main_scene_path + "icon66.png",
//     icon67: main_scene_path + "icon67.png",
//     icon68: main_scene_path + "icon68.png",
//     icon69: main_scene_path + "icon69.png",
//     icon70: main_scene_path + "icon70.png",
//     icon71: main_scene_path + "icon71.png",
//     icon72: main_scene_path + "icon72.png",
//     icon73: main_scene_path + "icon73.png",
//     icon74: main_scene_path + "icon74.png",
//     icon75: main_scene_path + "icon75.png",
//     icon76: main_scene_path + "icon76.png",
//     icon77: main_scene_path + "icon77.png",
//     icon78: main_scene_path + "icon78.png",
//     icon79: main_scene_path + "icon79.png",
//     icon80: main_scene_path + "icon80.png",
//     icon81: main_scene_path + "icon81.png",
//     icon82: main_scene_path + "icon82.png",
//     icon83: main_scene_path + "icon83.png",
//     icon84: main_scene_path + "icon84.png",
//     icon85: main_scene_path + "icon85.png",
//     icon86: main_scene_path + "icon86.png",
//     icon87: main_scene_path + "icon87.png",
//     icon88: main_scene_path + "icon88.png",
//     icon89: main_scene_path + "icon89.png",
//     icon90: main_scene_path + "icon90.png",
//     icon91: main_scene_path + "icon91.png",
//     icon92: main_scene_path + "icon92.png",
// //    icon93: main_scene_path + "icon93.png",
//     icon94: main_scene_path + "icon94.png",
// //    icon95: main_scene_path + "icon95.png",
//     icon96: main_scene_path + "icon96.png",
//     icon97: main_scene_path + "icon97.png",
//     icon98: main_scene_path + "icon98.png",
//     icon99: main_scene_path + "icon99.png",
//     icon100: main_scene_path + "icon100.png",
//     icon103: main_scene_path + "icon103.png",
//     icon104: main_scene_path + "icon104.png",
//     icon105: main_scene_path + "icon105.png",
//     icon106: main_scene_path + "icon106.png",
//     icon107: main_scene_path + "icon107.png",
//     icon108: main_scene_path + "icon108.png",
//     icon109: main_scene_path + "icon109.png",
//     icon110: main_scene_path + "icon110.png",
//     icon111: main_scene_path + "icon111.png",
//     icon112: main_scene_path + "icon112.png",
// //    icon113: main_scene_path + "icon113.png",
// //    icon114: main_scene_path + "icon114.png",
// //    icon115: main_scene_path + "icon115.png",
//     icon116: main_scene_path + "icon116.png",
//     icon117: main_scene_path + "icon117.png",
//     icon118: main_scene_path + "icon118.png",
//     icon119: main_scene_path + "icon119.png",
//     icon120: main_scene_path + "icon120.png",
//     icon121: main_scene_path + "icon121.png",
//     icon122: main_scene_path + "icon122.png",
//     icon123: main_scene_path + "icon123.png",
//     icon124: main_scene_path + "icon124.png",
//     icon125: main_scene_path + "icon125.png",
// //    icon126: main_scene_path + "icon126.png",
//     icon127: main_scene_path + "icon127.png",
//     icon128: main_scene_path + "icon128.png",
//     icon129: main_scene_path + "icon129.png",
//     icon130: main_scene_path + "icon130.png",
//     icon131: main_scene_path + "icon131.png",
// //    icon132: main_scene_path + "icon132.png",
//     icon133: main_scene_path + "icon133.png",
//     icon134: main_scene_path + "icon134.png",
//     icon135: main_scene_path + "icon135.png",
//     icon136: main_scene_path + "icon136.png",
//     icon137: main_scene_path + "icon137.png",
//     icon138: main_scene_path + "icon138.png",
//     icon139: main_scene_path + "icon139.png",
//     icon140: main_scene_path + "icon140.png",
// //    icon141: main_scene_path + "icon141.png",
//     icon142: main_scene_path + "icon142.png",
//     icon143: main_scene_path + "icon143.png",
// //    icon144: main_scene_path + "icon144.png",
//     icon145: main_scene_path + "icon145.png",
//     icon146: main_scene_path + "icon146.png",
//     icon147: main_scene_path + "icon147.png",
//     icon148: main_scene_path + "icon148.png",
//     icon149: main_scene_path + "icon149.png",
//     icon150: main_scene_path + "icon150.png",
//     icon151: main_scene_path + "icon151.png",
//     icon152: main_scene_path + "icon152.png",
//     icon153: main_scene_path + "icon153.png",
//     icon154: main_scene_path + "icon154.png",
//     icon155: main_scene_path + "icon155.png",
//     icon156: main_scene_path + "icon156.png",
//     icon157: main_scene_path + "icon157.png",
//     icon158: main_scene_path + "icon158.png",
//     icon159: main_scene_path + "icon159.png",
//     icon160: main_scene_path + "icon160.png",
//     icon161: main_scene_path + "icon161.png",
//     icon162: main_scene_path + "icon162.png",
//     icon163: main_scene_path + "icon163.png",
//     icon164: main_scene_path + "icon164.png",
//     icon165: main_scene_path + "icon165.png",
//     icon166: main_scene_path + "icon166.png",
//     icon167: main_scene_path + "icon167.png",
//     icon168: main_scene_path + "icon168.png",
//     icon169: main_scene_path + "icon169.png",
//     icon170: main_scene_path + "icon170.png",
//     icon171: main_scene_path + "icon171.png",
//     icon172: main_scene_path + "icon172.png",
//     icon173: main_scene_path + "icon173.png",
//     icon174: main_scene_path + "icon174.png",
//     icon175: main_scene_path + "icon175.png",
//     icon176: main_scene_path + "icon176.png",
//     icon177: main_scene_path + "icon177.png",
//     icon178: main_scene_path + "icon178.png",
//     icon179: main_scene_path + "icon179.png",
//     icon180: main_scene_path + "icon180.png",
//     icon181: main_scene_path + "icon181.png",
//     icon182: main_scene_path + "icon182.png",
//     icon183: main_scene_path + "icon183.png",
//     icon184: main_scene_path + "icon184.png",
//     icon185: main_scene_path + "icon185.png",
//     icon186: main_scene_path + "icon186.png",
//     icon187: main_scene_path + "icon187.png",
//     icon188: main_scene_path + "icon188.png",
//     icon189: main_scene_path + "icon189.png",
//     icon190: main_scene_path + "icon190.png",
//     icon191: main_scene_path + "icon191.png",
//     icon192: main_scene_path + "icon192.png",
//     icon193: main_scene_path + "icon193.png",
//     icon194: main_scene_path + "icon194.png",
//     icon195: main_scene_path + "icon195.png",
//     icon196: main_scene_path + "icon196.png",
//     icon197: main_scene_path + "icon197.png",
//     icon198: main_scene_path + "icon198.png",
//     icon199: main_scene_path + "icon199.png",
//     icon200: main_scene_path + "icon200.png",
//     icon201: main_scene_path + "icon201.png",
//     icon202: main_scene_path + "icon202.png",
//     icon203: main_scene_path + "icon203.png",
//     icon204: main_scene_path + "icon204.png",
//     icon205: main_scene_path + "icon205.png",
//     icon206: main_scene_path + "icon206.png",
//     icon207: main_scene_path + "icon207.png",
//     icon208: main_scene_path + "icon208.png",
//     icon209: main_scene_path + "icon209.png",
//     icon210: main_scene_path + "icon210.png",
//     icon211: main_scene_path + "icon211.png",
//     icon212: main_scene_path + "icon212.png",
//     icon213: main_scene_path + "icon213.png",
//     icon214: main_scene_path + "icon214.png",
//     icon215: main_scene_path + "icon215.png",
//     icon216: main_scene_path + "icon216.png",
//     icon217: main_scene_path + "icon217.png",
//     icon218: main_scene_path + "icon218.png",
//     icon219: main_scene_path + "icon219.png",
//     icon220: main_scene_path + "icon220.png",
//     icon221: main_scene_path + "icon221.png",
//     icon222: main_scene_path + "icon222.png",
//     icon223: main_scene_path + "icon223.png",
//     icon224: main_scene_path + "icon224.png",
//     icon225: main_scene_path + "icon225.png",
//     icon226: main_scene_path + "icon226.png",
//     icon227: main_scene_path + "icon227.png",
//     icon228: main_scene_path + "icon228.png",
//     icon229: main_scene_path + "icon229.png",
//     icon230: main_scene_path + "icon230.png",
//     icon231: main_scene_path + "icon231.png",
//     icon232: main_scene_path + "icon232.png",
//     icon233: main_scene_path + "icon233.png",
//     icon234: main_scene_path + "icon234.png",
//     icon235: main_scene_path + "icon235.png",
//     icon236: main_scene_path + "icon236.png",
//     icon237: main_scene_path + "icon237.png",
//     icon238: main_scene_path + "icon238.png",
//     icon239: main_scene_path + "icon239.png",
//     icon240: main_scene_path + "icon240.png",
//     icon241: main_scene_path + "icon241.png",
//     icon242: main_scene_path + "icon242.png",
//     icon243: main_scene_path + "icon243.png",
//     icon244: main_scene_path + "icon244.png",
//     icon245: main_scene_path + "icon245.png",
//     icon246: main_scene_path + "icon246.png",
//     icon247: main_scene_path + "icon247.png",
//     icon248: main_scene_path + "icon248.png",
//     icon249: main_scene_path + "icon249.png",
//     icon250: main_scene_path + "icon250.png",
//     icon251: main_scene_path + "icon251.png",
//     icon252: main_scene_path + "icon252.png",
//     icon253: main_scene_path + "icon253.png",
//     icon254: main_scene_path + "icon254.png",
//     icon255: main_scene_path + "icon255.png",
//     icon256: main_scene_path + "icon256.png",

    
    
 





    // 新手图片
    empty: effect_scene_path + "NewPlayer/" + "empty.png",
    hand: effect_scene_path + "NewPlayer/" + "hand.png",
    light: effect_scene_path + "NewPlayer/" + "light.png",
    yuanshen: effect_scene_path + "NewPlayer/" + "yuanshen.png",
    talking: effect_scene_path + "NewPlayer/" + "talking.png",


    //整理好的图片
    p1: effect_scene_path + "effect/" + "p1.png",
    p2: effect_scene_path + "effect/" + "p2.png",
    p3: effect_scene_path + "effect/" + "p3.png",
    p4: effect_scene_path + "effect/" + "p4.png",
    p5: effect_scene_path + "effect/" + "p5.png",
    p6: effect_scene_path + "effect/" + "p6.png",
    p7: effect_scene_path + "effect/" + "p7.png",
    p8: effect_scene_path + "effect/" + "p8.png",
    p9: effect_scene_path + "effect/" + "p9.png",
    p10: effect_scene_path + "effect/" + "p10.png",
    p11: effect_scene_path + "effect/" + "p11.png",
    p12: effect_scene_path + "effect/" + "p12.png",
    p13: effect_scene_path + "effect/" + "p13.png",
    p14: effect_scene_path + "effect/" + "p14.png",
    p15: effect_scene_path + "effect/" + "p15.png",
    p16: effect_scene_path + "effect/" + "p16.png",
    p17: effect_scene_path + "effect/" + "p17.png",
    p18: effect_scene_path + "effect/" + "p18.png",
    p19: effect_scene_path + "effect/" + "p19.png",
    p20: effect_scene_path + "effect/" + "p20.png",
    p21: effect_scene_path + "effect/" + "p21.png",
    p22: effect_scene_path + "effect/" + "p22.png",
    p23: effect_scene_path + "effect/" + "p23.png",
    p24: effect_scene_path + "effect/" + "p24.png", 
    p25: effect_scene_path + "effect/" + "p25.png",
    p26: effect_scene_path + "effect/" + "p26.png",
    p27: effect_scene_path + "effect/" + "p27.png",
    p28: effect_scene_path + "effect/" + "p28.png",
    p29: effect_scene_path + "effect/" + "p29.png",
    p30: effect_scene_path + "effect/" + "p30.png",
    p31: effect_scene_path + "effect/" + "p31.png",
    p32: effect_scene_path + "effect/" + "p32.png",
    p33: effect_scene_path + "effect/" + "p33.png",
    p34: effect_scene_path + "effect/" + "p34.png",
    p35: effect_scene_path + "effect/" + "p35.png",
    p36: effect_scene_path + "effect/" + "p36.png",
    p37: effect_scene_path + "effect/" + "p37.png",
    p38: effect_scene_path + "effect/" + "p38.png",
    p39: effect_scene_path + "effect/" + "p39.png",
    p40: effect_scene_path + "effect/" + "p40.png",
    p41: effect_scene_path + "effect/" + "p41.png",
    p42: effect_scene_path + "effect/" + "p42.png",
    p43: effect_scene_path + "effect/" + "p43.png",
    p44: effect_scene_path + "effect/" + "p44.png",
    p45: effect_scene_path + "effect/" + "p45.png",
    p46: effect_scene_path + "effect/" + "p46.png",
    p47: effect_scene_path + "effect/" + "p47.png",
    p48: effect_scene_path + "effect/" + "p48.png",
    p49: effect_scene_path + "effect/" + "p49.png",
    p50: effect_scene_path + "effect/" + "p50.png",
    p51: effect_scene_path + "effect/" + "p51.png",
    p52: effect_scene_path + "effect/" + "p52.png",
    p53: effect_scene_path + "effect/" + "p53.png",
    p54: effect_scene_path + "effect/" + "p54.png",
    p55: effect_scene_path + "effect/" + "p55.png",
    p56: effect_scene_path + "effect/" + "p56.png",
    p57: effect_scene_path + "effect/" + "p57.png",
    p58: effect_scene_path + "effect/" + "p58.png",
    p59: effect_scene_path + "effect/" + "p59.png",
    p60: effect_scene_path + "effect/" + "p60.png",
    p61: effect_scene_path + "effect/" + "p61.png",
    p62: effect_scene_path + "effect/" + "p62.png",
    p63: effect_scene_path + "effect/" + "p63.png",
    p64: effect_scene_path + "effect/" + "p64.png",
    p65: effect_scene_path + "effect/" + "p65.png",
    p66: effect_scene_path + "effect/" + "p66.png",
    p67: effect_scene_path + "effect/" + "p67.png",
    p68: effect_scene_path + "effect/" + "p68.png",
    p69: effect_scene_path + "effect/" + "p69.png",
    p70: effect_scene_path + "effect/" + "p70.png",
    p71: effect_scene_path + "effect/" + "p71.png",
    p72: effect_scene_path + "effect/" + "p72.png",
    p73: effect_scene_path + "effect/" + "p73.png",
    p74: effect_scene_path + "effect/" + "p74.png",
    p75: effect_scene_path + "effect/" + "p75.png",
    p76: effect_scene_path + "effect/" + "p76.png",
    p77: effect_scene_path + "effect/" + "p77.png",
    p78: effect_scene_path + "effect/" + "p78.png",
    p79: effect_scene_path + "effect/" + "p79.png",
    p80: effect_scene_path + "effect/" + "p80.png",
    p81: effect_scene_path + "effect/" + "p81.png",
    // p82: effect_scene_path + "effect/" + "p82.png",
    p83: effect_scene_path + "effect/" + "p83.png",
    p84: effect_scene_path + "effect/" + "p84.png",
    p85: effect_scene_path + "effect/" + "p85.png",
    p86: effect_scene_path + "effect/" + "p86.png",
    p87: effect_scene_path + "effect/" + "p87.png",
    p88: effect_scene_path + "effect/" + "p88.png",
    p89: effect_scene_path + "effect/" + "p89.png",
    p90: effect_scene_path + "effect/" + "p90.png",
    p91: effect_scene_path + "effect/" + "p91.png",
    p92: effect_scene_path + "effect/" + "p92.png",
    p93: effect_scene_path + "effect/" + "p93.png",
    p94: effect_scene_path + "effect/" + "p94.png",
    p95: effect_scene_path + "effect/" + "p95.png",
    p96: effect_scene_path + "effect/" + "p96.png",
    p97: effect_scene_path + "effect/" + "p97.png",
    p98: effect_scene_path + "effect/" + "p98.png",
    p99: effect_scene_path + "effect/" + "p99.png",
    p100: effect_scene_path + "effect/" + "p100.png",
    p101: effect_scene_path + "effect/" + "p101.png",
    p102: effect_scene_path + "effect/" + "p102.png",
    p103: effect_scene_path + "effect/" + "p103.png",
    p104: effect_scene_path + "effect/" + "p104.png",
    p105: effect_scene_path + "effect/" + "p105.png",
    p106: effect_scene_path + "effect/" + "p106.png",
    p107: effect_scene_path + "effect/" + "p107.png",
    p108: effect_scene_path + "effect/" + "p108.png",
    p109: effect_scene_path + "effect/" + "p109.png",
    p110: effect_scene_path + "effect/" + "p110.png",
    p111: effect_scene_path + "effect/" + "p111.png",
    p112: effect_scene_path + "effect/" + "p112.png",
    p113: effect_scene_path + "effect/" + "p113.png",
    p114: effect_scene_path + "effect/" + "p114.png",
    p115: effect_scene_path + "effect/" + "p115.png",
    p116: effect_scene_path + "effect/" + "p116.png",
    p117: effect_scene_path + "effect/" + "p117.png",
    p118: effect_scene_path + "effect/" + "p118.png",
    p119: effect_scene_path + "effect/" + "p119.png",
    p120: effect_scene_path + "effect/" + "p120.png",
    p121: effect_scene_path + "effect/" + "p121.png",
    p122: effect_scene_path + "effect/" + "p122.png",
    p123: effect_scene_path + "effect/" + "p123.png",
    p124: effect_scene_path + "effect/" + "p124.png",
    p125: effect_scene_path + "effect/" + "p125.png",
    p147: effect_scene_path + "effect/" + "p147.png",
    p149: effect_scene_path + "effect/" + "p149.png",
    p150: effect_scene_path + "effect/" + "p150.png",
    p151: effect_scene_path + "effect/" + "p151.png",
    p153: effect_scene_path + "effect/" + "p153.png",
    
    boss2_png: effect_scene_path + "effect/" + "boss2.png",
    boss2_plist: effect_scene_path + "effect/" + "boss2.plist",
    boss3_png: effect_scene_path + "effect/" + "boss3.png",
    boss3_plist: effect_scene_path + "effect/" + "boss3.plist",

    
    

    //UI特效
    up1: effect_scene_path + "uiEffect/" + "up1.png",
    up2: effect_scene_path + "uiEffect/" + "up2.png",
    up3: effect_scene_path + "uiEffect/" + "up3.png",
    up4: effect_scene_path + "uiEffect/" + "up4.png",
    up5: effect_scene_path + "uiEffect/" + "up5.png",
    up6: effect_scene_path + "uiEffect/" + "up6.png",
    up7: effect_scene_path + "uiEffect/" + "up7.png",
    up8: effect_scene_path + "uiEffect/" + "up8.png",
    up9: effect_scene_path + "uiEffect/" + "up9.png",
    up10: effect_scene_path + "uiEffect/" + "up10.png",
    up11: effect_scene_path + "uiEffect/" + "up11.png",
    up12: effect_scene_path + "uiEffect/" + "up12.png",
    up13: effect_scene_path + "uiEffect/" + "up13.png",
    up14: effect_scene_path + "uiEffect/" + "up14.png",
    up15: effect_scene_path + "uiEffect/" + "up15.png",
    up16: effect_scene_path + "uiEffect/" + "up16.png",
    up17: effect_scene_path + "uiEffect/" + "up17.png",
    up18: effect_scene_path + "uiEffect/" + "up18.png",
    up19: effect_scene_path + "uiEffect/" + "up19.png",
    up20: effect_scene_path + "uiEffect/" + "up20.png",
    up21: effect_scene_path + "uiEffect/" + "up21.png",
    up22: effect_scene_path + "uiEffect/" + "up22.png",
    up23: effect_scene_path + "uiEffect/" + "up23.png",
    up24: effect_scene_path + "uiEffect/" + "up24.png",
    up25: effect_scene_path + "uiEffect/" + "up25.png",
    up26: effect_scene_path + "uiEffect/" + "up26.png",
    up27: effect_scene_path + "uiEffect/" + "up27.png",
    up28: effect_scene_path + "uiEffect/" + "up28.png",
    up29: effect_scene_path + "uiEffect/" + "up29.png",
    up30: effect_scene_path + "uiEffect/" + "up30.png",
    up31: effect_scene_path + "uiEffect/" + "up31.png",
    up32: effect_scene_path + "uiEffect/" + "up32.png",
    up33: effect_scene_path + "uiEffect/" + "up33.png",
    up34: effect_scene_path + "uiEffect/" + "up34.png",
    up35: effect_scene_path + "uiEffect/" + "up35.png",
    up36: effect_scene_path + "uiEffect/" + "up36.png",
    up37: effect_scene_path + "uiEffect/" + "up37.png",
    up38: effect_scene_path + "uiEffect/" + "up38.png",
    up39: effect_scene_path + "uiEffect/" + "up39.png",
    up40: effect_scene_path + "uiEffect/" + "up40.png",
    up41: effect_scene_path + "uiEffect/" + "up41.png",
    up42: effect_scene_path + "uiEffect/" + "up42.png",
    up43: effect_scene_path + "uiEffect/" + "up43.png",
    up44: effect_scene_path + "uiEffect/" + "up44.png",
    up45: effect_scene_path + "uiEffect/" + "up45.png",
    up46: effect_scene_path + "uiEffect/" + "up46.png",
    up47: effect_scene_path + "uiEffect/" + "up47.png",
    up48: effect_scene_path + "uiEffect/" + "up48.png",
    up49: effect_scene_path + "uiEffect/" + "up49.png",
    up50: effect_scene_path + "uiEffect/" + "up50.png",
    up51: effect_scene_path + "uiEffect/" + "up51.png",
    up52: effect_scene_path + "uiEffect/" + "up52.png",
    up53: effect_scene_path + "uiEffect/" + "up53.png",
    up54: effect_scene_path + "uiEffect/" + "up54.png",
    up55: effect_scene_path + "uiEffect/" + "up55.png",
    up56: effect_scene_path + "uiEffect/" + "up56.png",
    up57: effect_scene_path + "uiEffect/" + "up57.png",
    up58: effect_scene_path + "uiEffect/" + "up58.png",
    up59: effect_scene_path + "uiEffect/" + "up59.png",
    up60: effect_scene_path + "uiEffect/" + "up60.png",
    up61: effect_scene_path + "uiEffect/" + "up61.png",
    up62: effect_scene_path + "uiEffect/" + "up62.png",
    up63: effect_scene_path + "uiEffect/" + "up63.png",
    up64: effect_scene_path + "uiEffect/" + "up64.png",
    up65: effect_scene_path + "uiEffect/" + "up65.png",
    up66: effect_scene_path + "uiEffect/" + "up66.png",
    up67: effect_scene_path + "uiEffect/" + "up67.png",
    up68: effect_scene_path + "uiEffect/" + "up68.png",
    up69: effect_scene_path + "uiEffect/" + "up69.png",
    up70: effect_scene_path + "uiEffect/" + "up70.png",
    up71: effect_scene_path + "uiEffect/" + "up71.png",
    up72: effect_scene_path + "uiEffect/" + "up72.png",
    up73: effect_scene_path + "uiEffect/" + "up73.png",
    up74: effect_scene_path + "uiEffect/" + "up74.png",
    up75: effect_scene_path + "uiEffect/" + "up75.png",
    up76: effect_scene_path + "uiEffect/" + "up76.png",
    up77: effect_scene_path + "uiEffect/" + "up77.png",
    up78: effect_scene_path + "uiEffect/" + "up78.png",
    up79: effect_scene_path + "uiEffect/" + "up79.png",
    up80: effect_scene_path + "uiEffect/" + "up80.png",
    up81: effect_scene_path + "uiEffect/" + "up81.png",
    up82: effect_scene_path + "uiEffect/" + "up82.png",
    up83: effect_scene_path + "uiEffect/" + "up83.png",
    up84: effect_scene_path + "uiEffect/" + "up84.png",
    up85: effect_scene_path + "uiEffect/" + "up85.png",
    up86: effect_scene_path + "uiEffect/" + "up86.png",
    up87: effect_scene_path + "uiEffect/" + "up87.png",
    up88: effect_scene_path + "uiEffect/" + "up88.png",
    up89: effect_scene_path + "uiEffect/" + "up89.png",
    up90: effect_scene_path + "uiEffect/" + "up90.png",
    up91: effect_scene_path + "uiEffect/" + "up91.png",
    up92: effect_scene_path + "uiEffect/" + "up92.png",
    up93: effect_scene_path + "uiEffect/" + "up93.png",
    
    up95: effect_scene_path + "uiEffect/" + "up95.png",
    up96: effect_scene_path + "uiEffect/" + "up96.png",
    up97: effect_scene_path + "uiEffect/" + "up97.png",
    up98: effect_scene_path + "uiEffect/" + "up98.png",
    up99: effect_scene_path + "uiEffect/" + "up99.png",
    up100: effect_scene_path + "uiEffect/" + "up100.png",
    up101: effect_scene_path + "uiEffect/" + "up101.png",
    up102: effect_scene_path + "uiEffect/" + "up102.png",
    up103: effect_scene_path + "uiEffect/" + "up103.png",
    up104: effect_scene_path + "uiEffect/" + "up104.png",
    up105: effect_scene_path + "uiEffect/" + "up105.png",
    up106: effect_scene_path + "uiEffect/" + "up106.png",
    up107: effect_scene_path + "uiEffect/" + "up107.png",
    up108: effect_scene_path + "uiEffect/" + "up108.png",
    up109: effect_scene_path + "uiEffect/" + "up109.png",
    up110: effect_scene_path + "uiEffect/" + "up110.png",
    up111: effect_scene_path + "uiEffect/" + "up111.png",
    up112: effect_scene_path + "uiEffect/" + "up112.png",
    up113: effect_scene_path + "uiEffect/" + "up113.png",
    up114: effect_scene_path + "uiEffect/" + "up114.png",
    up115: effect_scene_path + "uiEffect/" + "up115.png",
    up116: effect_scene_path + "uiEffect/" + "up116.png",
    up117: effect_scene_path + "uiEffect/" + "up117.png",
    up118: effect_scene_path + "uiEffect/" + "up118.png",
    up119: effect_scene_path + "uiEffect/" + "up119.png",
    up120: effect_scene_path + "uiEffect/" + "up120.png",
    up121: effect_scene_path + "uiEffect/" + "up121.png",
    up122: effect_scene_path + "uiEffect/" + "up122.png",
    up123: effect_scene_path + "uiEffect/" + "up123.png",
    up124: effect_scene_path + "uiEffect/" + "up124.png",
    up125: effect_scene_path + "uiEffect/" + "up125.png",
    up126: effect_scene_path + "uiEffect/" + "up126.png",
    up127: effect_scene_path + "uiEffect/" + "up127.png",
    up128: effect_scene_path + "uiEffect/" + "up128.png",
    up129: effect_scene_path + "uiEffect/" + "up129.png",
    up130: effect_scene_path + "uiEffect/" + "up130.png",
    up131: effect_scene_path + "uiEffect/" + "up131.png",
    up132: effect_scene_path + "uiEffect/" + "up132.png",
    up133: effect_scene_path + "uiEffect/" + "up133.png",
    up134: effect_scene_path + "uiEffect/" + "up134.png",
    up135: effect_scene_path + "uiEffect/" + "up135.png",
    up136: effect_scene_path + "uiEffect/" + "up136.png",
    up137: effect_scene_path + "uiEffect/" + "up137.png",
    up138: effect_scene_path + "uiEffect/" + "up138.png",
    up139: effect_scene_path + "uiEffect/" + "up139.png",
    up140: effect_scene_path + "uiEffect/" + "up140.png",
    up141: effect_scene_path + "uiEffect/" + "up141.png",
    up142: effect_scene_path + "uiEffect/" + "up142.png",
    up143: effect_scene_path + "uiEffect/" + "up143.png",
    up144: effect_scene_path + "uiEffect/" + "up144.png",
    up145: effect_scene_path + "uiEffect/" + "up145.png",
    up146: effect_scene_path + "uiEffect/" + "up146.png",
    up147: effect_scene_path + "uiEffect/" + "up147.png",
    up148: effect_scene_path + "uiEffect/" + "up148.png",
    up149: effect_scene_path + "uiEffect/" + "up149.png",
    up150: effect_scene_path + "uiEffect/" + "up150.png",
    up151: effect_scene_path + "uiEffect/" + "up151.png",
    up152: effect_scene_path + "uiEffect/" + "up152.png",
    up153: effect_scene_path + "uiEffect/" + "up153.png",
    
    up155: effect_scene_path + "uiEffect/" + "up155.png",
    up156: effect_scene_path + "uiEffect/" + "up156.png",
    up157: effect_scene_path + "uiEffect/" + "up157.png",
    up158: effect_scene_path + "uiEffect/" + "up158.png",
    up159: effect_scene_path + "uiEffect/" + "up159.png",
    up160: effect_scene_path + "uiEffect/" + "up160.png",
    up218: effect_scene_path + "uiEffect/" + "up218.png",
    up219: effect_scene_path + "uiEffect/" + "up219.png",
    up220: effect_scene_path + "uiEffect/" + "up220.png",
    up221: effect_scene_path + "uiEffect/" + "up221.png",
    bee_png: effect_scene_path + "uiEffect/" + "bee.png",
    bee_plist: effect_scene_path + "uiEffect/" + "bee.plist",
   

   



 
    
   
    tutorials1: ccb_scene_path + "tutorials1.ccbi",
    tutorials2: ccb_scene_path + "tutorials2.ccbi",
    tutorials3: ccb_scene_path + "tutorials3.ccbi",
    tutorials4: ccb_scene_path + "tutorials4.ccbi",
    tutorials5: ccb_scene_path + "tutorials5.ccbi",
    tutorials6: ccb_scene_path + "tutorials6.ccbi",
    tutorials7: ccb_scene_path + "tutorials7.ccbi",
    tutorials8: ccb_scene_path + "tutorials8.ccbi",
    tutorials9: ccb_scene_path + "tutorials9.ccbi",
    tutorials10: ccb_scene_path + "tutorials10.ccbi",
    tutorials11: ccb_scene_path + "tutorials11.ccbi",
    tutorials12: ccb_scene_path + "tutorials12.ccbi",
    tutorials13: ccb_scene_path + "tutorials13.ccbi",
    tutorials14: ccb_scene_path + "tutorials14.ccbi",
    tutorials15: ccb_scene_path + "tutorials15.ccbi",
    tutorials16: ccb_scene_path + "tutorials16.ccbi",
    tutorials17: ccb_scene_path + "tutorials17.ccbi",
    tutorials18: ccb_scene_path + "tutorials18.ccbi",
    tutorials19: ccb_scene_path + "tutorials19.ccbi",
    tutorials20: ccb_scene_path + "tutorials20.ccbi",
    tutorials21: ccb_scene_path + "tutorials21.ccbi",
    tutorials22: ccb_scene_path + "tutorials22.ccbi",
    tutorials23: ccb_scene_path + "tutorials23.ccbi",
    tutorials24: ccb_scene_path + "tutorials24.ccbi",
    tutorials25: ccb_scene_path + "tutorials25.ccbi",
    tutorials26: ccb_scene_path + "tutorials26.ccbi",
    tutorials27: ccb_scene_path + "tutorials27.ccbi",
   
    spiritNode: ccb_scene_path + "spiritNode.ccbi",
    battleNode: ccb_scene_path + "battleNode.ccbi",
    card20002: ccb_scene_path + "card20002.ccbi",


   
    

    //开场动画素材
    startAnimationRes1_png: effect_scene_path + "startAnimation/" + "startAnimationRes1.png",
    startAnimationRes1_plist: effect_scene_path + "startAnimation/" + "startAnimationRes1.plist",
    startAnimationRes2_png: effect_scene_path + "startAnimation/" + "startAnimationRes2.png",
    startAnimationRes2_plist: effect_scene_path + "startAnimation/" + "startAnimationRes2.plist",
    startAnimationRes3_png: effect_scene_path + "startAnimation/" + "startAnimationRes3.png",
    startAnimationRes3_plist: effect_scene_path + "startAnimation/" + "startAnimationRes3.plist",
    startAnimationRes4_png: effect_scene_path + "startAnimation/" + "startAnimationRes4.png",
    startAnimationRes4_plist: effect_scene_path + "startAnimation/" + "startAnimationRes4.plist",
    s1: effect_scene_path + "startAnimation/" + "s1.png",
    s2: effect_scene_path + "startAnimation/" + "s2.png",
    // s3: effect_scene_path + "startAnimation/" + "s3.png",
    s4: effect_scene_path + "startAnimation/" + "s4.png",
    // s5: effect_scene_path + "startAnimation/" + "s5.png",
    s6: effect_scene_path + "startAnimation/" + "s6.png",
    // s7: effect_scene_path + "startAnimation/" + "s7.png",
    // s8: effect_scene_path + "startAnimation/" + "s8.png",
    // s9: effect_scene_path + "startAnimation/" + "s9.png",
    // s10: effect_scene_path + "startAnimation/" + "s10.png",
    // s11: effect_scene_path + "startAnimation/" + "s11.png",
    s12: effect_scene_path + "startAnimation/" + "s12.png",
    // s13: effect_scene_path + "startAnimation/" + "s13.png",
    s14: effect_scene_path + "startAnimation/" + "s14.png",
    // s15: effect_scene_path + "startAnimation/" + "s15.png",
    // s16: effect_scene_path + "startAnimation/" + "s16.png",
    // s17: effect_scene_path + "startAnimation/" + "s17.png",
    // s18: effect_scene_path + "startAnimation/" + "s18.png",
    // s19: effect_scene_path + "startAnimation/" + "s19.png",
    // s20: effect_scene_path + "startAnimation/" + "s20.png",
    // s21: effect_scene_path + "startAnimation/" + "s21.png",
    // s22: effect_scene_path + "startAnimation/" + "s22.png",
    // s23: effect_scene_path + "startAnimation/" + "s23.png",
    // s24: effect_scene_path + "startAnimation/" + "s24.png",
    // s25: effect_scene_path + "startAnimation/" + "s25.png",
    s26: effect_scene_path + "startAnimation/" + "s26.png",
    s27: effect_scene_path + "startAnimation/" + "s27.png",
    s28: effect_scene_path + "startAnimation/" + "s28.png",
    s29: effect_scene_path + "startAnimation/" + "s29.png",
    s30: effect_scene_path + "startAnimation/" + "s30.png",
    // s31: effect_scene_path + "startAnimation/" + "s31.png",
    // s32: effect_scene_path + "startAnimation/" + "s32.png",
    // s33: effect_scene_path + "startAnimation/" + "s33.png",
    // s34: effect_scene_path + "startAnimation/" + "s34.png",
    // s35: effect_scene_path + "startAnimation/" + "s35.png",
    // s36: effect_scene_path + "startAnimation/" + "s36.png",
    s37: effect_scene_path + "startAnimation/" + "s37.png",
    s38: effect_scene_path + "startAnimation/" + "s38.png",
    // s39: effect_scene_path + "startAnimation/" + "s39.png",
    // s40: effect_scene_path + "startAnimation/" + "s40.png",
    // s41: effect_scene_path + "startAnimation/" + "s41.png",
    // s42: effect_scene_path + "startAnimation/" + "s42.png",
    // s43: effect_scene_path + "startAnimation/" + "s43.png",
    // s44: effect_scene_path + "startAnimation/" + "s44.png",
    // s45: effect_scene_path + "startAnimation/" + "s45.png",
    // s46: effect_scene_path + "startAnimation/" + "s46.png",
    // s47: effect_scene_path + "startAnimation/" + "s47.png",
    // s48: effect_scene_path + "startAnimation/" + "s48.png",
    // s49: effect_scene_path + "startAnimation/" + "s49.png",
    // s50: effect_scene_path + "startAnimation/" + "s50.png",
    // s51: effect_scene_path + "startAnimation/" + "s51.png",
    // s52: effect_scene_path + "startAnimation/" + "s52.png",
    s53: effect_scene_path + "startAnimation/" + "s53.png",
    // s54: effect_scene_path + "startAnimation/" + "s54.png",
    // s55: effect_scene_path + "startAnimation/" + "s55.png",
    // s56: effect_scene_path + "startAnimation/" + "s56.png",
    // s57: effect_scene_path + "startAnimation/" + "s57.png",
    // s58: effect_scene_path + "startAnimation/" + "s58.png",
    // s59: effect_scene_path + "startAnimation/" + "s59.png",
    // s60: effect_scene_path + "startAnimation/" + "s60.png",
    // s61: effect_scene_path + "startAnimation/" + "s61.png",
    // s62: effect_scene_path + "startAnimation/" + "s62.png",
    // s63: effect_scene_path + "startAnimation/" + "s63.png",
    // s64: effect_scene_path + "startAnimation/" + "s64.png",
    // s65: effect_scene_path + "startAnimation/" + "s65.png",
    // s66: effect_scene_path + "startAnimation/" + "s66.png",
    // s67: effect_scene_path + "startAnimation/" + "s67.png",
    // s68: effect_scene_path + "startAnimation/" + "s68.png",
    // s69: effect_scene_path + "startAnimation/" + "s69.png",
    // s70: effect_scene_path + "startAnimation/" + "s70.png",
    // s71: effect_scene_path + "startAnimation/" + "s71.png",
    // s72: effect_scene_path + "startAnimation/" + "s72.png",
    // s73: effect_scene_path + "startAnimation/" + "s73.png",
    // s74: effect_scene_path + "startAnimation/" + "s74.png",
    // s75: effect_scene_path + "startAnimation/" + "s75.png",
    // s76: effect_scene_path + "startAnimation/" + "s76.png",
    // s77: effect_scene_path + "startAnimation/" + "s77.png",
    // s78: effect_scene_path + "startAnimation/" + "s78.png",
    // s79: effect_scene_path + "startAnimation/" + "s79.png",
    // s80: effect_scene_path + "startAnimation/" + "s80.png",
    // s81: effect_scene_path + "startAnimation/" + "s81.png",
    // s82: effect_scene_path + "startAnimation/" + "s82.png",
    // s83: effect_scene_path + "startAnimation/" + "s83.png",
    // s84: effect_scene_path + "startAnimation/" + "s84.png",
    // s85: effect_scene_path + "startAnimation/" + "s85.png",
    // s86: effect_scene_path + "startAnimation/" + "s86.png",
    // s87: effect_scene_path + "startAnimation/" + "s87.png",
    // s88: effect_scene_path + "startAnimation/" + "s88.png",
    // s89: effect_scene_path + "startAnimation/" + "s89.png",
    // s90: effect_scene_path + "startAnimation/" + "s90.png",
    s91: effect_scene_path + "startAnimation/" + "s91.png",
    // s92: effect_scene_path + "startAnimation/" + "s92.png",
    // s93: effect_scene_path + "startAnimation/" + "s93.png",
    // s94: effect_scene_path + "startAnimation/" + "s94.png",
    // s95: effect_scene_path + "startAnimation/" + "s95.png",
    s96: effect_scene_path + "startAnimation/" + "s96.png",
    // s97: effect_scene_path + "startAnimation/" + "s97.png",
    // s98: effect_scene_path + "startAnimation/" + "s98.png",
    // s99: effect_scene_path + "startAnimation/" + "s99.png",
    // s100: effect_scene_path + "startAnimation/" + "s100.png",
    // s101: effect_scene_path + "startAnimation/" + "s101.png",
    // s102: effect_scene_path + "startAnimation/" + "s102.png",
    // s103: effect_scene_path + "startAnimation/" + "s103.png",
    // s104: effect_scene_path + "startAnimation/" + "s104.png",
    // s105: effect_scene_path + "startAnimation/" + "s105.png",
    // s106: effect_scene_path + "startAnimation/" + "s106.png",
    // s107: effect_scene_path + "startAnimation/" + "s107.png",
    // s108: effect_scene_path + "startAnimation/" + "s108.png",
    // s109: effect_scene_path + "startAnimation/" + "s109.png",
    // s110: effect_scene_path + "startAnimation/" + "s110.png",
    // s111: effect_scene_path + "startAnimation/" + "s111.png",
    // s112: effect_scene_path + "startAnimation/" + "s112.png",
    s113: effect_scene_path + "startAnimation/" + "s113.png",
    // s114: effect_scene_path + "startAnimation/" + "s114.png",
    // s115: effect_scene_path + "startAnimation/" + "s115.png",
    // s116: effect_scene_path + "startAnimation/" + "s116.png",
    // s117: effect_scene_path + "startAnimation/" + "s117.png",
    // s118: effect_scene_path + "startAnimation/" + "s118.png",
    // s119: effect_scene_path + "startAnimation/" + "s119.png",
    // s120: effect_scene_path + "startAnimation/" + "s120.png",
    // s121: effect_scene_path + "startAnimation/" + "s121.png",
    // s122: effect_scene_path + "startAnimation/" + "s122.png",
    // s123: effect_scene_path + "startAnimation/" + "s123.png",
    // s124: effect_scene_path + "startAnimation/" + "s124.png",
    // s125: effect_scene_path + "startAnimation/" + "s125.png",
    // s126: effect_scene_path + "startAnimation/" + "s126.png",
    // s127: effect_scene_path + "startAnimation/" + "s127.png",
    // s128: effect_scene_path + "startAnimation/" + "s128.png",
    s129: effect_scene_path + "startAnimation/" + "s129.png",
    // s130: effect_scene_path + "startAnimation/" + "s130.png",
    s131: effect_scene_path + "startAnimation/" + "s131.png",
    // s132: effect_scene_path + "startAnimation/" + "s132.png",
    // s133: effect_scene_path + "startAnimation/" + "s133.png",
    // s134: effect_scene_path + "startAnimation/" + "s134.png",
    // s135: effect_scene_path + "startAnimation/" + "s135.png",
    // s136: effect_scene_path + "startAnimation/" + "s136.png",
    // s137: effect_scene_path + "startAnimation/" + "s137.png",
    // s138: effect_scene_path + "startAnimation/" + "s138.png",
    // s139: effect_scene_path + "startAnimation/" + "s139.png",

    








    // 完成特效
    battleEffect1: ccb_scene_path + "battleEffect1.ccbi", 
    battleEffect2: ccb_scene_path + "battleEffect2.ccbi", 
    battleEffect3: ccb_scene_path + "battleEffect3.ccbi", 
    battleEffect4: ccb_scene_path + "battleEffect4.ccbi", 
    battleEffect5: ccb_scene_path + "battleEffect5.ccbi",
    battleEffect6: ccb_scene_path + "battleEffect6.ccbi", 
    battleEffect7: ccb_scene_path + "battleEffect7.ccbi", 
    battleEffect8: ccb_scene_path + "battleEffect8.ccbi", 
    battleEffect9: ccb_scene_path + "battleEffect9.ccbi", 
    
    effect1_1: ccb_scene_path + "effect1_1.ccbi", 
    effect1_2: ccb_scene_path + "effect1_2.ccbi", 
    effect2_1: ccb_scene_path + "effect2_1.ccbi", 
    effect2_2: ccb_scene_path + "effect2_2.ccbi",
    effect3: ccb_scene_path + "effect3.ccbi", 
    effect4_1: ccb_scene_path + "effect4_1.ccbi",
    effect4_2: ccb_scene_path + "effect4_2.ccbi",
    effect5_1: ccb_scene_path + "effect5_1.ccbi",
    effect5_2: ccb_scene_path + "effect5_2.ccbi",
    effect6_1: ccb_scene_path + "effect6_1.ccbi",
    effect6_2: ccb_scene_path + "effect6_2.ccbi",
    effect7_1: ccb_scene_path + "effect7_1.ccbi",
    effect7_2: ccb_scene_path + "effect7_2.ccbi",
    effect8: ccb_scene_path + "effect8.ccbi",
    effect9: ccb_scene_path + "effect9.ccbi",
    effect300_1: ccb_scene_path + "effect300_1.ccbi", 
    effect300_2: ccb_scene_path + "effect300_2.ccbi", 
    effect301_1: ccb_scene_path + "effect301_1.ccbi", 
    effect301_2: ccb_scene_path + "effect301_2.ccbi", 
    effect302_1: ccb_scene_path + "effect302_1.ccbi",
    effect302_2: ccb_scene_path + "effect302_2.ccbi",
    effect302_3: ccb_scene_path + "effect302_3.ccbi",
    effect400_1: ccb_scene_path + "effect400_1.ccbi", 
    effect400_2: ccb_scene_path + "effect400_2.ccbi", 
    effect401_1: ccb_scene_path + "effect401_1.ccbi", 
    effect401_2: ccb_scene_path + "effect401_2.ccbi",
    effect402: ccb_scene_path + "effect402.ccbi",
    effect403: ccb_scene_path + "effect403.ccbi",
    effect404_1: ccb_scene_path + "effect404_1.ccbi",
    effect404_2: ccb_scene_path + "effect404_2.ccbi",
    effect405_1: ccb_scene_path + "effect405_1.ccbi",
    effect405_2: ccb_scene_path + "effect405_2.ccbi",
    effect405_3: ccb_scene_path + "effect405_3.ccbi",
    effect500_1: ccb_scene_path + "effect500_1.ccbi",
    effect500_2: ccb_scene_path + "effect500_2.ccbi",
    effect501: ccb_scene_path + "effect501.ccbi",
    effect502: ccb_scene_path + "effect502.ccbi",
    effect503_1: ccb_scene_path + "effect503_1.ccbi",
    effect503_2: ccb_scene_path + "effect503_2.ccbi",
    effect600_1: ccb_scene_path + "effect600_1.ccbi",
    effect600_2: ccb_scene_path + "effect600_2.ccbi",
    effect601_1: ccb_scene_path + "effect601_1.ccbi",
    effect601_2: ccb_scene_path + "effect601_2.ccbi",
    effect700_1: ccb_scene_path + "effect700_1.ccbi",
    effect700_2: ccb_scene_path + "effect700_2.ccbi",
    effect701_1: ccb_scene_path + "effect701_1.ccbi",
    effect701_2: ccb_scene_path + "effect701_2.ccbi",
    effect701_3: ccb_scene_path + "effect701_3.ccbi",
    effect702_1: ccb_scene_path + "effect702_1.ccbi",
    effect702_2: ccb_scene_path + "effect702_2.ccbi",
    effect702_3: ccb_scene_path + "effect702_3.ccbi",
    effect800: ccb_scene_path + "effect800.ccbi",
    effect801: ccb_scene_path + "effect801.ccbi",
    effect802: ccb_scene_path + "effect802.ccbi",
    effect803: ccb_scene_path + "effect803.ccbi",
    effect804: ccb_scene_path + "effect804.ccbi",
    effect805: ccb_scene_path + "effect805.ccbi",
    effect806: ccb_scene_path + "effect806.ccbi",
    effect807_1: ccb_scene_path + "effect807_1.ccbi",
    effect807_2: ccb_scene_path + "effect807_2.ccbi",
    effect1001_3: ccb_scene_path + "effect1001_3.ccbi",
    effect1800_1: ccb_scene_path + "effect1800_1.ccbi",
    effect1800_2: ccb_scene_path + "effect1800_2.ccbi",
    effect1800_3: ccb_scene_path + "effect1800_3.ccbi",
    effect1800_4: ccb_scene_path + "effect1800_4.ccbi",
    exploreEffect1: ccb_scene_path + "exploreEffect1.ccbi",
    exploreEffect2: ccb_scene_path + "exploreEffect2.ccbi",
    exploreEffect3: ccb_scene_path + "exploreEffect3.ccbi",
    exploreEffect4: ccb_scene_path + "exploreEffect4.ccbi",
    exploreEffect5: ccb_scene_path + "exploreEffect5.ccbi",
    exploreEffect6: ccb_scene_path + "exploreEffect6.ccbi",
    exploreEffect7: ccb_scene_path + "exploreEffect7.ccbi",
    exploreEffect8: ccb_scene_path + "exploreEffect8.ccbi",

    uiEffect1: ccb_scene_path + "uiEffect1.ccbi", 
    uiEffect2: ccb_scene_path + "uiEffect2.ccbi", 
    uiEffect3: ccb_scene_path + "uiEffect3.ccbi", 
    uiEffect4: ccb_scene_path + "uiEffect4.ccbi", 
    uiEffect5: ccb_scene_path + "uiEffect5.ccbi", 
    uiEffect6: ccb_scene_path + "uiEffect6.ccbi",
    uiEffect7: ccb_scene_path + "uiEffect7.ccbi",
    uiEffect8: ccb_scene_path + "uiEffect8.ccbi",
    uiEffect9: ccb_scene_path + "uiEffect9.ccbi",
    uiEffect10: ccb_scene_path + "uiEffect10.ccbi",
    uiEffect11: ccb_scene_path + "uiEffect11.ccbi",
    uiEffect12: ccb_scene_path + "uiEffect12.ccbi",
    uiEffect13: ccb_scene_path + "uiEffect13.ccbi",
    uiEffect14: ccb_scene_path + "uiEffect14.ccbi",
    uiEffect15: ccb_scene_path + "uiEffect15.ccbi",
    uiEffect16: ccb_scene_path + "uiEffect16.ccbi",
    uiEffect17: ccb_scene_path + "uiEffect17.ccbi",
    uiEffect18: ccb_scene_path + "uiEffect18.ccbi",
    uiEffect19: ccb_scene_path + "uiEffect19.ccbi",
    uiEffect20: ccb_scene_path + "uiEffect20.ccbi",
    uiEffect21: ccb_scene_path + "uiEffect21.ccbi",
    uiEffect22: ccb_scene_path + "uiEffect22.ccbi",
    uiEffect23: ccb_scene_path + "uiEffect23.ccbi",
    uiEffect24: ccb_scene_path + "uiEffect24.ccbi",
    uiEffect25: ccb_scene_path + "uiEffect25.ccbi",
    uiEffect26: ccb_scene_path + "uiEffect26.ccbi",
    uiEffect27: ccb_scene_path + "uiEffect27.ccbi",
    uiEffect28: ccb_scene_path + "uiEffect28.ccbi",
    uiEffect29: ccb_scene_path + "uiEffect29.ccbi",
    uiEffect30: ccb_scene_path + "uiEffect30.ccbi",
    uiEffect31: ccb_scene_path + "uiEffect31.ccbi",
    uiEffect32: ccb_scene_path + "uiEffect32.ccbi",
    uiEffect33: ccb_scene_path + "uiEffect33.ccbi",
    uiEffect34: ccb_scene_path + "uiEffect34.ccbi",
    uiEffect35: ccb_scene_path + "uiEffect35.ccbi",
    uiEffect36: ccb_scene_path + "uiEffect36.ccbi",
    uiEffect37: ccb_scene_path + "uiEffect37.ccbi",
    uiEffect38: ccb_scene_path + "uiEffect38.ccbi",
    uiEffect39: ccb_scene_path + "uiEffect39.ccbi",
    uiEffect40: ccb_scene_path + "uiEffect40.ccbi",
    uiEffect41: ccb_scene_path + "uiEffect41.ccbi",
    uiEffect42: ccb_scene_path + "uiEffect42.ccbi",
    uiEffect43: ccb_scene_path + "uiEffect43.ccbi",
    uiEffect44: ccb_scene_path + "uiEffect44.ccbi",
    uiEffect45: ccb_scene_path + "uiEffect45.ccbi",
    uiEffect46: ccb_scene_path + "uiEffect46.ccbi",
    uiEffect47: ccb_scene_path + "uiEffect47.ccbi",
    uiEffect48: ccb_scene_path + "uiEffect48.ccbi",
    uiEffect49: ccb_scene_path + "uiEffect49.ccbi",
    uiEffect50: ccb_scene_path + "uiEffect50.ccbi",
    uiEffect51: ccb_scene_path + "uiEffect51.ccbi",
    uiEffect52: ccb_scene_path + "uiEffect52.ccbi",
    uiEffect53: ccb_scene_path + "uiEffect53.ccbi",
    uiEffect54: ccb_scene_path + "uiEffect54.ccbi",
    uiEffect55: ccb_scene_path + "uiEffect55.ccbi",
    uiEffect56: ccb_scene_path + "uiEffect56.ccbi",
    uiEffect57: ccb_scene_path + "uiEffect57.ccbi",
    uiEffect58: ccb_scene_path + "uiEffect58.ccbi",
    uiEffect59: ccb_scene_path + "uiEffect59.ccbi",
    uiEffect60: ccb_scene_path + "uiEffect60.ccbi",
    uiEffect61: ccb_scene_path + "uiEffect61.ccbi",
    uiEffect62: ccb_scene_path + "uiEffect62.ccbi",
    uiEffect63: ccb_scene_path + "uiEffect63.ccbi",
    uiEffect64: ccb_scene_path + "uiEffect64.ccbi",
    uiEffect65: ccb_scene_path + "uiEffect65.ccbi",
    uiEffect66: ccb_scene_path + "uiEffect66.ccbi",
    uiEffect67: ccb_scene_path + "uiEffect67.ccbi",
    uiEffect68: ccb_scene_path + "uiEffect68.ccbi",
    uiEffect69: ccb_scene_path + "uiEffect69.ccbi",
    uiEffect70: ccb_scene_path + "uiEffect70.ccbi",
    uiEffect71: ccb_scene_path + "uiEffect71.ccbi",
    uiEffect72: ccb_scene_path + "uiEffect72.ccbi",
    uiEffect73: ccb_scene_path + "uiEffect73.ccbi",
    uiEffect74: ccb_scene_path + "uiEffect74.ccbi",
    uiEffect75: ccb_scene_path + "uiEffect75.ccbi",
    uiEffect76: ccb_scene_path + "uiEffect76.ccbi",
    uiEffect77: ccb_scene_path + "uiEffect77.ccbi",
    uiEffect78: ccb_scene_path + "uiEffect78.ccbi",
    uiEffect79: ccb_scene_path + "uiEffect79.ccbi",
    uiEffect80: ccb_scene_path + "uiEffect80.ccbi",
    uiEffect81: ccb_scene_path + "uiEffect81.ccbi",
    uiEffect82: ccb_scene_path + "uiEffect82.ccbi",
    uiEffect83: ccb_scene_path + "uiEffect83.ccbi",
    uiEffect84: ccb_scene_path + "uiEffect84.ccbi",
    uiEffect85: ccb_scene_path + "uiEffect85.ccbi",
    uiEffect91: ccb_scene_path + "uiEffect91.ccbi",
    uiEffect93: ccb_scene_path + "uiEffect93.ccbi",
    uiEffect96: ccb_scene_path + "uiEffect96.ccbi",
    

    //开场动画
    startAnimation1: ccb_scene_path + "startAnimation1.ccbi",
    startAnimation2: ccb_scene_path + "startAnimation2.ccbi",
    startAnimation3: ccb_scene_path + "startAnimation3.ccbi",
    startAnimation4: ccb_scene_path + "startAnimation4.ccbi",
    startAnimation5: ccb_scene_path + "startAnimation5.ccbi",


    //技能特效测试素材
    1: test_scene_path + "res/" + "1.png",
    2: test_scene_path + "res/" + "2.png",
    3: test_scene_path + "res/" + "3.png",
    4: test_scene_path + "res/" + "4.png",
    5: test_scene_path + "res/" + "5.png",
    6: test_scene_path + "res/" + "6.png",
    7: test_scene_path + "res/" + "7.png",
    8: test_scene_path + "res/" + "8.png",
    9: test_scene_path + "res/" + "9.png",
    
    11: test_scene_path + "res/" + "11.png",
    12: test_scene_path + "res/" + "12.png",
    13: test_scene_path + "res/" + "13.png",
    14: test_scene_path + "res/" + "14.png",
    15: test_scene_path + "res/" + "15.png",
    16: test_scene_path + "res/" + "16.png",
    17: test_scene_path + "res/" + "17.png",
    18: test_scene_path + "res/" + "18.png",
    19: test_scene_path + "res/" + "19.png",
    20: test_scene_path + "res/" + "20.png",
    21: test_scene_path + "res/" + "21.png",
    29: test_scene_path + "res/" + "29.png",
    30: test_scene_path + "res/" + "30.png",
    35: test_scene_path + "res/" + "35.png",
    37: test_scene_path + "res/" + "37.png",
    40: test_scene_path + "res/" + "40.png",
    42: test_scene_path + "res/" + "42.png",
    46: test_scene_path + "res/" + "46.png",
    47: test_scene_path + "res/" + "47.png",
    48: test_scene_path + "res/" + "48.png",
    49: test_scene_path + "res/" + "49.png",
    50: test_scene_path + "res/" + "50.png",
    51: test_scene_path + "res/" + "51.png",
    52: test_scene_path + "res/" + "52.png",
    53: test_scene_path + "res/" + "53.png",
    54: test_scene_path + "res/" + "54.png",
    56: test_scene_path + "res/" + "56.png",
    60: test_scene_path + "res/" + "60.png",
    61: test_scene_path + "res/" + "61.png",
    62: test_scene_path + "res/" + "62.png",
    63: test_scene_path + "res/" + "63.png",
    
    65: test_scene_path + "res/" + "65.png",
    66: test_scene_path + "res/" + "66.png",
    70: test_scene_path + "res/" + "70.png",
    76: test_scene_path + "res/" + "76.png",
    77: test_scene_path + "res/" + "77.png",
    78: test_scene_path + "res/" + "78.png",
    79: test_scene_path + "res/" + "79.png",
    80: test_scene_path + "res/" + "80.png",
    82: test_scene_path + "res/" + "82.png",
    83: test_scene_path + "res/" + "83.png",
    84: test_scene_path + "res/" + "84.png",
    88: test_scene_path + "res/" + "88.png",
    89: test_scene_path + "res/" + "89.png",
    92: test_scene_path + "res/" + "92.png",
    93: test_scene_path + "res/" + "93.png",
    95: test_scene_path + "res/" + "95.png",
    105: test_scene_path + "res/" + "105.png",
    106: test_scene_path + "res/" + "106.png",
    107: test_scene_path + "res/" + "107.png",
    108: test_scene_path + "res/" + "108.png",
    109: test_scene_path + "res/" + "109.png",
    110: test_scene_path + "res/" + "110.png",



    //技能特效
    texiao1: test_scene_path + "ccb/" + "texiao1.ccbi",
    texiao2: test_scene_path + "ccb/" + "texiao2.ccbi",
    texiao3: test_scene_path + "ccb/" + "texiao3.ccbi",
    texiao4: test_scene_path + "ccb/" + "texiao4.ccbi",
    texiao5: test_scene_path + "ccb/" + "texiao5.ccbi",
    texiao6: test_scene_path + "ccb/" + "texiao6.ccbi",
    texiao7: test_scene_path + "ccb/" + "texiao7.ccbi",
    texiao8: test_scene_path + "ccb/" + "texiao8.ccbi",
    texiao9: test_scene_path + "ccb/" + "texiao9.ccbi",
    texiao11: test_scene_path + "ccb/" + "texiao11.ccbi",
    texiao12: test_scene_path + "ccb/" + "texiao12.ccbi",
    texiao13: test_scene_path + "ccb/" + "texiao13.ccbi",
    texiao15: test_scene_path + "ccb/" + "texiao15.ccbi",
    texiao16: test_scene_path + "ccb/" + "texiao16.ccbi",
    texiao17: test_scene_path + "ccb/" + "texiao17.ccbi",
    texiao19: test_scene_path + "ccb/" + "texiao19.ccbi",
    texiao20: test_scene_path + "ccb/" + "texiao20.ccbi",
    texiao21: test_scene_path + "ccb/" + "texiao21.ccbi",
    texiao22: test_scene_path + "ccb/" + "texiao22.ccbi",
    texiao23: test_scene_path + "ccb/" + "texiao23.ccbi",
    texiao24: test_scene_path + "ccb/" + "texiao24.ccbi",
    texiao25: test_scene_path + "ccb/" + "texiao25.ccbi",
    texiao26: test_scene_path + "ccb/" + "texiao26.ccbi",
    texiao27: test_scene_path + "ccb/" + "texiao27.ccbi",
    texiao28: test_scene_path + "ccb/" + "texiao28.ccbi",
    texiao29: test_scene_path + "ccb/" + "texiao29.ccbi",
    texiao30: test_scene_path + "ccb/" + "texiao30.ccbi",
    texiao31: test_scene_path + "ccb/" + "texiao31.ccbi",
    texiao32: test_scene_path + "ccb/" + "texiao32.ccbi",
    texiao36: test_scene_path + "ccb/" + "texiao36.ccbi",

};

var main_scene_res = [
    //image
    //plist
    //fnt
    //tmx
    //bgm
    //effect
];

var cardResIdList = [
    2, 3, 7, 9, 12, 18, 19, 20, 22, 25, 28, 30, 31, 32, 34, 36, 38, 39, 43, 44, 49, 50, 51
];

for (var cardIndex = 0; cardIndex < cardResIdList.length; ++cardIndex) {
    var cardId = cardResIdList[cardIndex];

    main_scene_image["card" + cardId + "_head1"] = main_scene_path + "card" + cardId + "_head1.png";
    main_scene_image["card" + cardId + "_head2"] = main_scene_path + "card" + cardId + "_head2.png";
    main_scene_image["card" + cardId + "_head3"] = main_scene_path + "card" + cardId + "_head3.png";

    main_scene_image["card" + cardId + "_half1"] = main_scene_path + "card" + cardId + "_half1.png";
    main_scene_image["card" + cardId + "_half2"] = main_scene_path + "card" + cardId + "_half2.png";
    main_scene_image["card" + cardId + "_half3"] = main_scene_path + "card" + cardId + "_half3.png";

    main_scene_image["card" + cardId + "_full1"] = main_scene_path + "card" + cardId + "_full1.png";
    main_scene_image["card" + cardId + "_full2"] = main_scene_path + "card" + cardId + "_full2.png";
    main_scene_image["card" + cardId + "_full3"] = main_scene_path + "card" + cardId + "_full3.png";

    main_scene_image["card" + cardId + "_skill"] = main_scene_path + "card" + cardId + "_skill.png";
}

for (var taskId = 1; taskId <= 50; ++taskId) {
    main_scene_image["task" + taskId] = main_scene_path + "task" + taskId + ".png";
}

for (var key in main_scene_image) {
    main_scene_res.push({src: main_scene_image[key]});
}


//字体
main_scene_res.push({src: "../res/font/skillName.fnt"});
main_scene_res.push({src: "../res/font/skillName.png"});
main_scene_res.push({src: "../res/font/tipNumber.fnt"});
main_scene_res.push({src: "../res/font/tipNumber.png"});
main_scene_res.push({src: "../res/font/UInumber.fnt"});
main_scene_res.push({src: "../res/font/UInumber.png"});
main_scene_res.push({src: "../res/font/AchievementWord.fnt"});
main_scene_res.push({src: "../res/font/AchievementWord.png"});
main_scene_res.push({src: "../res/font/levelWord.fnt"});
main_scene_res.push({src: "../res/font/levelWord.png"});



//音效
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_angry_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_boom_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_ding_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_funny_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_insert_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_keep_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_money_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_noword_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_peaches_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_pop_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_rock_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_shardow_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_smalltree_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_treelight_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_wordinsert_sound.wav"});
main_scene_res.push({src: "../res/sound/startAnimationsound/startAnimation_breaktree_sound.wav"});






