// Generated by CoffeeScript 1.6.3
var Manager, async, dao, _;
var express = require('express');
app = express();
dao = app.get('dao');

async = require('async');

_ = require('underscore');

Manager = (function() {
  function Manager() {}

  Manager.deleteCards = function(ids, cb) {
    if (!_.isArray(ids)) {
      ids = [ids];
    }
    return async.map(ids, function(id, done) {
      return dao.card["delete"]({
        where: {
          id: id
        }
      }, function(err, result) {
        if (err !== null) {
          return done(err, false);
        }
        return done(null, result);
      });
    }, function(err, results) {
      if (err !== null) {
        return cb(err, false);
      } else {
        return cb(null, _.some(results));
      }
    });
  };

  Manager.getCards = function(ids, cb) {
    if (!_.isArray(ids)) {
      ids = [ids];
    }
    return async.map(ids, function(id, done) {
      return dao.card.getCardInfo({
        where: {
          id: id
        }
      }, done);
    }, function(err, cards) {
      if (err !== null) {
        return cb(err, null);
      } else {
        return cb(null, cards);
      }
    });
  };

  Manager.getCardInfo = function(id, cb) {
    return dao.card.getCardInfo({
      where: {
        id: id
      }
    }, cb);
  };

  return Manager;

})();

module.exports = Manager;
