// Generated by CoffeeScript 1.6.3
var Cache, PlayerCache, cache;

Cache = require('../common/cache');

cache = new Cache();

PlayerCache = (function() {
  function PlayerCache() {}

  PlayerCache.put = function(player) {
    return cache.put(player.id, player);
  };

  PlayerCache.get = function(key) {
    return cache.get(key);
  };

  PlayerCache.del = function(key) {
    return cache.del(key);
  };

  PlayerCache.clear = function() {
    return cache.clear();
  };

  PlayerCache.size = function() {
    return cache.size();
  };

  PlayerCache.all = function() {
    return cache.all();
  };

  return PlayerCache;

})();

module.exports = PlayerCache;
