// Generated by CoffeeScript 1.6.3
var playerConfig, _;

playerConfig = require('../../../config/data/player');

_ = require('underscore');

exports.addEvents = function(player) {
  player.on('power.consume', function() {
    var interval, now, ply, power, resumePoint, times;
    ply = player;
    interval = playerConfig.POWER_RESUME.interval;
    power = ply.power;
    now = Date.now();
    if ((power.time + interval) <= now) {
      times = parseInt((now - power.time) / interval);
      resumePoint = playerConfig.POWER_RESUME.point;
      ply.resumePower(resumePoint * times);
      return ply.save();
    }
  });
  player.on('power.give', function() {
    var cur_hour, givePoint, hours, interval;
    givePoint = playerConfig.POWER_GIVE.point;
    hours = playerConfig.POWER_GIVE.hours;
    interval = playerConfig.POWER_GIVE.interval;
    cur_hour = (new Date()).getHours();
    if (_.contains(hours, cur_hour) && !player.hasGive('power_' + cur_hour)) {
      player.givePower(cur_hour, givePoint);
      return player.save();
    }
  });
  player.on('lineUp.change', function() {
    player.updateAbility();
    player.activeGroupEffect();
    player.activeSpiritorEffect();
    return player.save();
  });
  player.emit('lineUp.change');
};
